from src.zoolab import Zoolab
import json

def create_zoolab(path:str):
    zoolab = Zoolab()
    areas = [
        'besaid', 'kilika', 'via mihen', 'via micorocciosa', 'via djose',
        'piana dei lampi', 'macalania', 'bikanel', 'piana della bonaccia',
        'grotta del crepaccio', 'monte gagazet', 'zanarkand', 'dentro sin',
        'rovine di omega'
    ]
    for area in areas:
        zoolab.add_area(area)

    zoolab.add_area('other', 257)

    zoolab.add_fiend('Besaid', 'dingo', 'Fenril')
    zoolab.add_fiend('Besaid', 'condor', 'Pterix')
    zoolab.add_fiend('Besaid', 'budino d\'acqua', 'Budino Jumbo')

    zoolab.add_fiend('kilika', 'Deinonychus', "Ornitorestes")
    zoolab.add_fiend('kilika', "Ape Killer", "Honet")
    zoolab.add_fiend('kilika', "Elemento Giallo", "Elemento Nega")
    zoolab.add_fiend('kilika', "Balsamiko")

    zoolab.add_fiend('Via Mihen', "Mihen Phang", "Fenril")
    zoolab.add_fiend('Via Mihen', "Ipiria", "Ornitorestes")
    zoolab.add_fiend('Via Mihen', "Occhio fluttuante", "Unioculum")
    zoolab.add_fiend('Via Mihen', "Elemento Bianco", "Elemento Nega")
    zoolab.add_fiend('Via Mihen', "Rarth", "Tanket")
    zoolab.add_fiend('Via Mihen', "Vivre", "Fefnil")
    zoolab.add_fiend('Via Mihen', "Piros", "Re Piros")
    zoolab.add_fiend('Via Mihen', "Bikorno", "Juggernaut")

    zoolab.add_fiend('Via Micorocciosa', "Raptor", "Ornitorestes")
    zoolab.add_fiend('Via Micorocciosa', "Gandharva", "Vizalsha")
    zoolab.add_fiend('Via Micorocciosa', "Budino di tuono", "Budino Jumbo")
    zoolab.add_fiend('Via Micorocciosa', "Elemento rosso", "Elemento Nega")
    zoolab.add_fiend('Via Micorocciosa', "Ramashut", "Fefnil")
    zoolab.add_fiend('Via Micorocciosa', "Fungongo", "Sonnellino")
    zoolab.add_fiend('Via Micorocciosa', "Garuda")

    zoolab.add_fiend('Via Djose', "Garm", "Fenril")
    zoolab.add_fiend('Via Djose', "Simurgh", "Pterix")
    zoolab.add_fiend('Via Djose', "Lesmathor", "Honet")
    zoolab.add_fiend('Via Djose', "Budino di neve", "Budino Jumbo")
    zoolab.add_fiend('Via Djose', "Bunyips", "Tanket")
    zoolab.add_fiend('Via Djose', "Basilisk")
    zoolab.add_fiend('Via Djose', "Ochu")

    zoolab.add_fiend('Piana dei lampi', "Meryujin", "Ornitorestes")
    zoolab.add_fiend('Piana dei lampi', "Aroj", "Vizalsha")
    zoolab.add_fiend('Piana dei lampi', "Buel", "Unioculum")
    zoolab.add_fiend('Piana dei lampi', "Elemento dorato", "Elemento Nega")
    zoolab.add_fiend('Piana dei lampi', "Kusarik", "Fefnil")
    zoolab.add_fiend('Piana dei lampi', "Larva")
    zoolab.add_fiend('Piana dei lampi', "Thytan", "Clod D'acciaio")
    zoolab.add_fiend('Piana dei lampi', "Kyactus")

    zoolab.add_fiend('Macalania', "Lupo delle nevi", "Fenril")
    zoolab.add_fiend('Macalania', "Shumelke")
    zoolab.add_fiend('Macalania', "Vespa", "Honet")
    zoolab.add_fiend('Macalania', "Occhio diabolico", "Unioculum")
    zoolab.add_fiend('Macalania', "Budino di Ghiaccio", "Budino Jumbo")
    zoolab.add_fiend('Macalania', "Elemento Blu", "Elemento Nega")
    zoolab.add_fiend('Macalania', "Mulfus", "Tanket")
    zoolab.add_fiend('Macalania', "Mafut", "Tanket")
    zoolab.add_fiend('Macalania', "Kushipos")
    zoolab.add_fiend('Macalania', "Chimera")

    zoolab.add_fiend('Bikanel', "Lupo del deserto", "Fenril")
    zoolab.add_fiend('Bikanel', "Alcione", "Pterix")
    zoolab.add_fiend('Bikanel', "Mushuhushu", "Fefnil")
    zoolab.add_fiend('Bikanel', "Zuu")
    zoolab.add_fiend('Bikanel', "Anellidus")
    zoolab.add_fiend('Bikanel', "Kyactus?")

    zoolab.add_fiend('Piana della Bonaccia', "Scoor", "Fenril")
    zoolab.add_fiend('Piana della Bonaccia', "Nebiros", "Honet")
    zoolab.add_fiend('Piana della Bonaccia', "Budino di fiamme", "Budino Jumbo")
    zoolab.add_fiend('Piana della Bonaccia', "Shred", "Tanket")
    zoolab.add_fiend('Piana della Bonaccia', "Anacondar")
    zoolab.add_fiend('Piana della Bonaccia', "Hoga")
    zoolab.add_fiend('Piana della Bonaccia', "Iaguaro")
    zoolab.add_fiend('Piana della Bonaccia', "Chimera Brain")
    zoolab.add_fiend('Piana della Bonaccia', "Molboro")

    zoolab.add_fiend('Grotta del Crepaccio', "Yowie", "Ornitorestes")
    zoolab.add_fiend('Grotta del Crepaccio', "Galkimasela", "Vizalsha")
    zoolab.add_fiend('Grotta del Crepaccio', "Elemento scuro", "Elemento Nega")
    zoolab.add_fiend('Grotta del Crepaccio', "Heg", "Fefnil")
    zoolab.add_fiend('Grotta del Crepaccio', "Son", "Sonnellino")
    zoolab.add_fiend('Grotta del Crepaccio', "Varaha", "Juggernaut")
    zoolab.add_fiend('Grotta del Crepaccio', "Epej")
    zoolab.add_fiend('Grotta del Crepaccio', "Fantasma")
    zoolab.add_fiend('Grotta del Crepaccio', "Tomberry")

    zoolab.add_fiend('Monte Gagazet', "Mal Bernardo", "Fenril")
    zoolab.add_fiend('Monte Gagazet', "Alyman", "Unioculum")
    zoolab.add_fiend('Monte Gagazet', "Budino oscuro", "Budino Jumbo")
    zoolab.add_fiend('Monte Gagazet', "Granad", "Re Piros")
    zoolab.add_fiend('Monte Gagazet', "Grat")
    zoolab.add_fiend('Monte Gagazet', "Grendel", "Juggernaut")
    zoolab.add_fiend('Monte Gagazet', "Ashoor")
    zoolab.add_fiend('Monte Gagazet', "Mandragora")
    zoolab.add_fiend('Monte Gagazet', "Behemoth")
    zoolab.add_fiend('Monte Gagazet', "Splasher")
    zoolab.add_fiend('Monte Gagazet', "Aquelous")
    zoolab.add_fiend('Monte Gagazet', "Echeneis")

    zoolab.add_fiend('Dentro Sin', "Exoray", "Sonnellino")
    zoolab.add_fiend('Dentro Sin', "Alyadin")
    zoolab.add_fiend('Dentro Sin', "Ultra Might (spada normale)", "Clod D'acciaio")
    zoolab.add_fiend('Dentro Sin', "Ultra Might (spada stella)", "Clod D'acciaio")
    zoolab.add_fiend('Dentro Sin', "Demomonolix")
    zoolab.add_fiend('Dentro Sin', "Molboro il Grande")
    zoolab.add_fiend('Dentro Sin', "Barbatos")
    zoolab.add_fiend('Dentro Sin', "Adamanthart")
    zoolab.add_fiend('Dentro Sin', "King Behemoth")

    zoolab.add_fiend('Rovine di Omega', "Zauras", "Ornitorestes")
    zoolab.add_fiend('Rovine di Omega', "Byurobolos", "Re Piros")
    zoolab.add_fiend('Rovine di Omega', "Desflot", "Unioculum")
    zoolab.add_fiend('Rovine di Omega', "Elemento nero", "Elemento Nega")
    zoolab.add_fiend('Rovine di Omega', "Haruma", "Tanket")
    zoolab.add_fiend('Rovine di Omega', "Esprit")
    zoolab.add_fiend('Rovine di Omega', "Mechy")
    zoolab.add_fiend('Rovine di Omega', "Master Iaguaro")
    zoolab.add_fiend('Rovine di Omega', "Mastro Tomberry")
    zoolab.add_fiend('Rovine di Omega', "Varna")

    zoolab.set_fiend_property("bribe", "Adamanthart", ("1.360.000", "1 Qualitosfera"))
    zoolab.set_fiend_property("bribe", "Alcione", ("10.750", "2 Megafenice"))
    zoolab.set_fiend_property("bribe", "Alyadin", ("555.550", "60 Vento d'Oltremondo"))
    zoolab.set_fiend_property("bribe", "Alyman", ("70.000", "6 Vento d'Oltremondo"))
    zoolab.set_fiend_property("bribe", "Anacondar", ("145.000", "16 Acqua Curativa"))
    zoolab.set_fiend_property("bribe", "Anellidus", ("1.125.000", "15 Equazione Cubica"))
    zoolab.set_fiend_property("bribe", "Ape Killer", ("2.750", "1 Zanna Velenosa"))
    zoolab.set_fiend_property("bribe", "Aquelous", ("127.500", "16 Fluido Rigenerante"))
    zoolab.set_fiend_property("bribe", "Aroj", ("5.000", "4 Razzo Fulminante"))
    zoolab.set_fiend_property("bribe", "Ashoor", ("425.000", "80 Fluido Energetico"))
    zoolab.set_fiend_property("bribe", "Autoarmatura", ("217.500", "99 Albhedina"))
    zoolab.set_fiend_property("bribe", "Autoartigliere", ("70.000", "40 Albhedina"))
    zoolab.set_fiend_property("bribe", "Autocacciatore", ("137.500", "60 Albhedina"))
    zoolab.set_fiend_property("bribe", "Autocommander", ("92.500", "2 Porta sul Domani"))
    zoolab.set_fiend_property("bribe", "Autoguardiano", ("32.000", "50 Granata"))
    zoolab.set_fiend_property("bribe", "Autoscout", ("68.750", "1 Porta sul Domani"))
    zoolab.set_fiend_property("bribe", "Balsamiko", ("19.500", "8 Panacea"))
    zoolab.set_fiend_property("bribe", "BalsamikoGrasso", ("318.750", "99 Panacea"))
    zoolab.set_fiend_property("bribe", "Barbatos", ("2.375.000", "20 Telesfera"))
    zoolab.set_fiend_property("bribe", "Basilisk", ("50.625", "24 Granata fossile"))
    zoolab.set_fiend_property("bribe", "Behemoth", ("575.000", "30 Passosfera lv 2"))
    zoolab.set_fiend_property("bribe", "Bikorno", ("46.875", "60 Granpozione"))
    zoolab.set_fiend_property("bribe", "Bikorno (CovoAlbhed)", ("94.875", "25 Megapozione"))
    zoolab.set_fiend_property("bribe", "Budino d'Acqua", ("7.875", "15 Idromagilite"))
    zoolab.set_fiend_property("bribe", "Budino d'Acqua (Canale purificatorio Yuna)", ("50.625", "2 Idromagilite"))
    zoolab.set_fiend_property("bribe", "Budino diFiamme", ("37.500", "10 Magmagilite"))
    zoolab.set_fiend_property("bribe", "Budino diGhiaccio", ("33.750", "9 Criomagilite"))
    zoolab.set_fiend_property("bribe", "Budino diNeve", ("15.000", "10 Vento Antartico"))
    zoolab.set_fiend_property("bribe", "Budino diTuono", ("11.250", "8 Razzo Fulminante"))
    zoolab.set_fiend_property("bribe", "Budino Oscuro", ("320.000", "2MBiancosfera"))
    zoolab.set_fiend_property("bribe", "Buel", ("5.750", "2 Stricnina"))
    zoolab.set_fiend_property("bribe", "Bunyips", ("10.000", "16 Hypellina"))
    zoolab.set_fiend_property("bribe", "Byurobolos", ("500.000", "36Eliomagilite"))
    zoolab.set_fiend_property("bribe", "Chimera", ("131.250", "10 Nettare Magico"))
    zoolab.set_fiend_property("bribe", "Chimera (CovoAlbhed)", ("225.000", "15Controchiave"))
    zoolab.set_fiend_property("bribe", "Chimera Brain", ("245.000", "2 Passosfera lv 4"))
    zoolab.set_fiend_property("bribe", "Condor", ("2.375", "3 Lacrimogeno"))
    zoolab.set_fiend_property("bribe", "Dedalarva", ("55.550", "14Idromagilite"))
    zoolab.set_fiend_property("bribe", "Defender", ("300.000", "20 Nettare Energetico"))
    zoolab.set_fiend_property("bribe", "Defender Zero", ("1.057.500", "5 Portafoglio Gonfio"))
    zoolab.set_fiend_property("bribe", "Deinonychus", ("3.500", "2 Granata Fossile"))
    zoolab.set_fiend_property("bribe", "Demomonolix", ("1.125.000", "40 Passosfera lv 3"))
    zoolab.set_fiend_property("bribe", "Desflot", ("167.500", "10 Anima delBaro"))
    zoolab.set_fiend_property("bribe", "Dingo", ("3.125", "4 Melatonina"))
    zoolab.set_fiend_property("bribe", "Echeneis", ("250.000", "1Parametrosfera"))
    zoolab.set_fiend_property("bribe", "Elemento Bianco", ("9.750", "7 Vento Antartico"))
    zoolab.set_fiend_property("bribe", "Elemento Blu", ("375.000", "19Idromagilite"))
    zoolab.set_fiend_property("bribe", "Elemento dorato", ("30.000", "20 Razzo Fulminante"))
    zoolab.set_fiend_property("bribe", "Elemento Giallo", ("7.500", "6 Razzo Fulminante"))
    zoolab.set_fiend_property("bribe", "Elemento Nero", ("190.000", "2 MNerosfera"))
    zoolab.set_fiend_property("bribe", "Elemento Rosso", ("11.250", "8 Anima di Piros"))
    zoolab.set_fiend_property("bribe", "Elemento Scuro", ("45.000", "3Gamberosfera"))
    zoolab.set_fiend_property("bribe", "Epej", ("217.500", "25 Vento d'Oltremondo"))
    zoolab.set_fiend_property("bribe", "Esprit", ("250.000", "10 Duostella"))
    zoolab.set_fiend_property("bribe", "Exoray", ("185.000", "30 Turboetere"))
    zoolab.set_fiend_property("bribe", "Fantasma", ("249.975", "38 Megafenice"))
    zoolab.set_fiend_property("bribe", "Fungongo", ("13.500", "2 Turboetere"))
    zoolab.set_fiend_property("bribe", "Galkimasela", ("22.000", "4 Passosfera lv 1"))
    zoolab.set_fiend_property("bribe", "Gandharva", ("3.700", "3 Razzo Fulminante"))
    zoolab.set_fiend_property("bribe", "Garm", ("6.000", "7 Melatonina"))
    zoolab.set_fiend_property("bribe", "Garuda", ("100.000", "99Lacrimogeno"))
    zoolab.set_fiend_property("bribe", "Granad", ("187.500", "12Eliomagilite"))
    zoolab.set_fiend_property("bribe", "Grat", ("100.000", "40 Panacea"))
    zoolab.set_fiend_property("bribe", "Grendel", ("237.500", "60Megapozione"))
    zoolab.set_fiend_property("bribe", "Guardia Guado (Tempio di Macalania)", ("50.000", "10 Etere"))
    zoolab.set_fiend_property("bribe", "Guardia Guado (Covo Albhed)", ("65.000", "30Extrapozione"))
    zoolab.set_fiend_property("bribe", "Haruma", ("325.000", "20Examagilite"))
    zoolab.set_fiend_property("bribe", "Heg", ("50.000", "12 Clessidra d'Oro"))
    zoolab.set_fiend_property("bribe", "Hoga", ("235.000", "50 Fluido Energetico"))
    zoolab.set_fiend_property("bribe", "Iaguaro", ("150.000", "2 Empatosfera"))
    zoolab.set_fiend_property("bribe", "Ipiria", ("4.500", "3 Granata Fossile"))
    zoolab.set_fiend_property("bribe", "King Behemoth", ("1.687.500", "14 Triostella"))
    zoolab.set_fiend_property("bribe", "Kusarik", ("11.125", "20 Clessidra d'Argento"))
    zoolab.set_fiend_property("bribe", "Kushipos", ("67.500", "1 Megaelisir"))
    zoolab.set_fiend_property("bribe", "Larva", ("37.450", "10 Spina Iperica"))
    zoolab.set_fiend_property("bribe", "Lesmathor", ("5.000", "2 Zanna Velenosa"))
    zoolab.set_fiend_property("bribe", "Lumbrikus", ("2.000.000", "2Materioscura"))
    zoolab.set_fiend_property("bribe", "Lupo del Deserto", ("11.250", "12 Melatonina"))
    zoolab.set_fiend_property("bribe", "Lupo delle Nevi", ("10.000", "11 Melatonina"))
    zoolab.set_fiend_property("bribe", "Mafut", ("17.750", "28 Hypellina"))
    zoolab.set_fiend_property("bribe", "Mal Bernardo", ("45.000", "20 Onirolina"))
    zoolab.set_fiend_property("bribe", "Mandragora", ("775.000", "24Gamberosfera"))
    zoolab.set_fiend_property("bribe", "MasterIaguaro", ("325.000", "1 Onnisfera"))
    zoolab.set_fiend_property("bribe", "MastroTomberry", ("1.200.000", "3 Pendulum"))
    zoolab.set_fiend_property("bribe", "Mechy", ("450.000", "60 Piuma di Chocobo"))
    zoolab.set_fiend_property("bribe", "Meryujin", ("6.625", "4 Granata fossile"))
    zoolab.set_fiend_property("bribe", "Mihen Phang", ("4.000", "5 Melatonina"))
    zoolab.set_fiend_property("bribe", "Molboro", ("675.000", "4 Ali per l'Ignoto"))
    zoolab.set_fiend_property("bribe", "Molboro ilGrande", ("1.600.000", "8 Ali per l'Ignoto"))
    zoolab.set_fiend_property("bribe", "Mulfus", ("14.500", "24 Hypellina"))
    zoolab.set_fiend_property("bribe", "Mushuhushu", ("17.000", "5 Clessidra d'Oro"))
    zoolab.set_fiend_property("bribe", "Nebiros", ("17.500", "6 Zanna Velenosa"))
    zoolab.set_fiend_property("bribe", "OcchioDiabolico", ("7.750", "3 Stricnina"))
    zoolab.set_fiend_property("bribe", "OcchioDiabolico (Covo Albhed)", ("10.750", "4 Stricnina"))
    zoolab.set_fiend_property("bribe", "OcchioFluttuante", ("3.500", "1 Stricnina"))
    zoolab.set_fiend_property("bribe", "OcchioMalvagio", ("9.500", "12 Mina Tacet"))
    zoolab.set_fiend_property("bribe", "Ochu", ("180.000", "70 Panacea"))
    zoolab.set_fiend_property("bribe", "Ochu Smarrito", ("116.225", "80 Panacea"))
    zoolab.set_fiend_property("bribe", "Octopus", ("112.500", "20 Fluido Rigenerante"))
    zoolab.set_fiend_property("bribe", "Paludomafut", ("21.250", "32 Hypellina"))
    zoolab.set_fiend_property("bribe", "Phlegyas", ("42.000", "6 Fluido Rigenerante"))
    zoolab.set_fiend_property("bribe", "Piranha", ("1.250", "1Idromagilite"))
    zoolab.set_fiend_property("bribe", "Piranha x2", ("2.500", "1Idromagilite"))
    zoolab.set_fiend_property("bribe", "Piranha x3", ("3.750", "2 Idromagilite"))
    zoolab.set_fiend_property("bribe", "Piros", ("21.250", "16 Anima di Piros"))
    zoolab.set_fiend_property("bribe", "Piros (CovoAlbhed)", ("55.000", "14Magmagilite"))
    zoolab.set_fiend_property("bribe", "Ramashut", ("6.875", "10 Clessidra d'Argento"))
    zoolab.set_fiend_property("bribe", "Raptor", ("5.000", "3 Granata Fossile"))
    zoolab.set_fiend_property("bribe", "Rarth", ("6.000", "10 Hypellina"))
    zoolab.set_fiend_property("bribe", "Remora", ("75.000", "20Idromagilite"))
    zoolab.set_fiend_property("bribe", "Sahagin (Canale Purificatorio Yuna)", ("34.500", "8Idromagilite"))
    zoolab.set_fiend_property("bribe", "Sahagin (Canale Purificatorio Tidus)", ("9.500", "3Idromagilite"))
    zoolab.set_fiend_property("bribe", "Scoor", ("25.000", "12 Onirolina"))
    zoolab.set_fiend_property("bribe", "Shred", ("48.750", "50 Hypellina"))
    zoolab.set_fiend_property("bribe", "Shumelke", ("9.250", "5 Granata Fossile"))
    zoolab.set_fiend_property("bribe", "Shumelke Krypt", ("13.750", "6 Granata Fossile"))
    zoolab.set_fiend_property("bribe", "Simurgh", ("5.000", "5 Lacrimogeno"))
    zoolab.set_fiend_property("bribe", "Son", ("102.000", "16 Turboetere"))
    zoolab.set_fiend_property("bribe", "Splasher", ("5.000", "4 Squame di Drago"))
    zoolab.set_fiend_property("bribe", "Splasher x2", ("10.000", "8 Squame di Drago"))
    zoolab.set_fiend_property("bribe", "Splasher x3", ("15.000", "12 Squame di Drago"))
    zoolab.set_fiend_property("bribe", "Thytan", ("90.000", "1 Filtro Energetico"))
    zoolab.set_fiend_property("bribe", "Tomberry", ("337.500", "2 Amuleto"))
    zoolab.set_fiend_property("bribe", "Ultima Weapon", ("2.499.975", "99 Pendulum"))
    zoolab.set_fiend_property("bribe", "Ultra Might(Spada stella)", ("900.000", "10 Filtro Energetico"))
    zoolab.set_fiend_property("bribe", "Ultra Might(Spada normale)", ("900.000", "10 Filtro Magico"))
    zoolab.set_fiend_property("bribe", "Unità 97", ("92.500", "16 Etere"))
    zoolab.set_fiend_property("bribe", "Unità 99", ("67.500", "10 Etere"))
    zoolab.set_fiend_property("bribe", "UnitàBlindata 11", ("155.000", "12 Elisir"))
    zoolab.set_fiend_property("bribe", "UnitàBlindata 63", ("105.000", "8 Elisir"))
    zoolab.set_fiend_property("bribe", "Varaha", ("217.500", "60Extrapozione"))
    zoolab.set_fiend_property("bribe", "Varna", ("1.400.000", "2 Megaelisir"))
    zoolab.set_fiend_property("bribe", "Vespa", ("9.000", "3 Zanna Velenosa"))
    zoolab.set_fiend_property("bribe", "Vihur", ("6.375", "10 Clessidra d'Argento"))
    zoolab.set_fiend_property("bribe", "Yowie", ("22.500", "12 Granata Fossile"))
    zoolab.set_fiend_property("bribe", "Zauras", ("196.250", "10 Carta d'Identità"))
    zoolab.set_fiend_property("bribe", "Zuu", ("450.000", "2 Tecnisfera"))

    zoolab.set_fiend_property("rewards", "ADAMANTHART", ("Perforazione, Consumo ½ MP", "Riserva Shell, Riserva Protect, HP +20%"))
    zoolab.set_fiend_property("rewards", "ALCIONE", ("Spot, Perforazione, Induttore V", "DIF Blind, DIF Mag +5%"))
    zoolab.set_fiend_property("rewards", "ALYADIN", ("Perforazione, ATT Mag +5%, ATT Mag +10%,Induttore M", "MP+10%, Incontri 0"))
    zoolab.set_fiend_property("rewards", "ALYMAN", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Att Fis +5%, ATT Mag +5%", "DIF Caos"))
    zoolab.set_fiend_property("rewards", "ANACONDAR", ("Perforazione, ATT Pietra, ATT Fis +5%, ATT Mag+5%", "DIF Pietra"))
    zoolab.set_fiend_property("rewards", "ANELLIDUS", ("Perforazione, ATT Lentezza, ATT Fis +5%, ATTMag +5%", "HP +10%, Autopozione"))
    zoolab.set_fiend_property("rewards", "ANIMA", ("Perforazione, ATT Blind, ATT Mutismo, ATTSonno", "DIF Blind, DIF Mutismo, DIF Sonno"))
    zoolab.set_fiend_property("rewards", "APE KILLER", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Veleno, MP +5%"))
    zoolab.set_fiend_property("rewards", "AQUELOUS", ("Perforazione, ATT Fis +5%, ATT Mag +10%", "MP +10%, Autopanacea"))
    zoolab.set_fiend_property("rewards", "AROJ", ("Perforazione, Tuonattacco, Induttore M", "Tuono -50%, Immunotuono, DIF Mag +5%"))
    zoolab.set_fiend_property("rewards", "ASHOOR", ("Perforazione, ATT Fis +5%, ATT Mag +5%,Contrattacco", "Riserva Haste, HP +10%"))
    zoolab.set_fiend_property("rewards", "AUTOARMATURA", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva: Parafire, Parathund, Paraidro,Parabliz, Shell, Protect, Reflex"))
    zoolab.set_fiend_property("rewards", "AUTOARTIGLIERE", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva: Parafire, Parathund, Paraidro,Parabliz, Shell, Protect, Reflex"))
    zoolab.set_fiend_property("rewards", "AUTOCACCIATORE", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva: Parafire, Parathund, Paraidro,Parabliz, Shell, Protect, Reflex"))
    zoolab.set_fiend_property("rewards", "AUTOCOMMANDER", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva: Parafire, Parathund, Paraidro,Parabliz"))
    zoolab.set_fiend_property("rewards", "AUTOGUARDIANO", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva: Parafire, Parathund, Paraidro,Parabliz"))
    zoolab.set_fiend_property("rewards", "AUTOSCOUT", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva: Parafire, Parathund, Paraidro,Parabliz"))
    zoolab.set_fiend_property("rewards", "BALSAMIKO", ("Perforazione, ATT Veleno, ATT Fis +3%, ATT Mag+3%", "DIF Veleno, HP +5%"))
    zoolab.set_fiend_property("rewards", "BALSAMIKO GRASSO", ("Perforazione, ATT Veleno, ATT Fis +3%, ATT Mag+3%", "DIF Veleno, HP +5%, HP +10%"))
    zoolab.set_fiend_property("rewards", "BARBATOS", ("Perforazione", "MP +20%"))
    zoolab.set_fiend_property("rewards", "BASILISK", ("Perforazione, ATT Pietra, ATT Fis +3%, ATT Mag+3%", "DIF Pietra, MP +5%"))
    zoolab.set_fiend_property("rewards", "BEHEMOTH", ("Perforazione, ATT Zombie, ATT Fis +5%, ATT Mag+5%, Riserva Turbo", "Riserva Shell, Riserva Protect, Riserva Reflex"))
    zoolab.set_fiend_property("rewards", "BIKORNO", ("Perforazione, Fuocattacco, ATT Mutismo,Induttore A", "HP +5%"))
    zoolab.set_fiend_property("rewards", "BIKORNO", ("Perforazione, Fuocattacco, ATT Mutismo,Induttore A", "HP +5%, HP +10%"))
    zoolab.set_fiend_property("rewards", "BIRAN RONSO", ("Perforazione", "MP +20%"))
    zoolab.set_fiend_property("rewards", "BRACCIO", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%"))
    zoolab.set_fiend_property("rewards", "BRACCIO DX DI SIN", ("Perforazione, ATT Pietra +", "DIF Pietra +"))
    zoolab.set_fiend_property("rewards", "BRACCIO SX DI SIN", ("Perforazione, ATT Veleno +", "DIF Veleno +"))
    zoolab.set_fiend_property("rewards", "BUDINO D'ACQUA", ("Perforazione, Acquattacco, Induttore M", "Acqua -50%, Immunoacqua"))
    zoolab.set_fiend_property("rewards", "BUDINO D'ACQUA", ("Perforazione, Acquattacco, Induttore M", "Acqua -50%"))
    zoolab.set_fiend_property("rewards", "BUDINO DI FIAMME", ("Perforazione, Fuocattacco, Induttore M", "Fuoco +50%, Immunofuoco"))
    zoolab.set_fiend_property("rewards", "BUDINO DI GHIACCIO", ("Perforazione, Gelattacco, Induttore M", "Gelo +50%, Immunofuoco"))
    zoolab.set_fiend_property("rewards", "BUDINO DI NEVE", ("Perforazione, Gelattacco, Induttore M", "Gelo +50%, Immunofuoco"))
    zoolab.set_fiend_property("rewards", "BUDINO DI TUONO", ("Perforazione, Tuonattacco, Induttore M", "Gelo +50%, Immunotuono"))
    zoolab.set_fiend_property("rewards", "BUDINO OSCURO", ("Perforazione, ATT Mag +5%, ATT Mag +10%,Induttore M", "MP +10%, MP +20%"))
    zoolab.set_fiend_property("rewards", "BUEL", ("Perforaz., Fuocattac., Tuonattac., Acquattac.,Gelattac., ATT Fis +3%, ATT Mag +3%, Induttore V", "DIF Caos, MP +5%"))
    zoolab.set_fiend_property("rewards", "BUNYIPS", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Berserk, DIF Fis +3%"))
    zoolab.set_fiend_property("rewards", "CANNONIERE ALBHED", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Arte medica", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%"))
    zoolab.set_fiend_property("rewards", "CHIMERA", ("Perforazione,ATT Mag +5%, ATT Mag +10%, Induttore M", "DIF Mag +10%"))
    zoolab.set_fiend_property("rewards", "CHIMERA", ("Perforazione, ATT Mag +5%, ATT Mag +10%, Induttore M", "DIF Mag +10%"))
    zoolab.set_fiend_property("rewards", "CHIMERA BRAIN", ("Perforazione, ATT Mag +5%, ATT Mag +10%, Induttore M", "DIF Mag +10%"))
    zoolab.set_fiend_property("rewards", "CONDOR", ("Spot, Perforazione, Induttore V", "DIF Blind, DIF Mag +3%"))
    zoolab.set_fiend_property("rewards", "CUSTODE CELESTE", ("Perforazione, Consumo 1/2 MP", "MP +10%"))
    zoolab.set_fiend_property("rewards", "CUSTODE DEL LIMBO", ("Perforazione, Fuocattacco, Tuonattacco, Acquattacco, Gelattacco", "Immunofuoco, Immunotuono, Immunoacqua, Immunogelo"))
    zoolab.set_fiend_property("rewards", "DEDALARVA", ("Perforazione, ATT Sonno", "DIF Sonno, DIF Mag +5%"))
    zoolab.set_fiend_property("rewards", "DEFENDER", ("Perforazione, ATT Fis +3%, ATT Fis +5%, Induttore E", "Riserva Protect, DIF Fis +10%"))
    zoolab.set_fiend_property("rewards", "DEFENDER ZERO", ("Perforazione, ATT Fis +3%, ATT Fis +5%, ATT Fis +10%, Induttore E", "Riserva Protect, DIF Fis +10%"))
    zoolab.set_fiend_property("rewards", "DEFENSOR", ("Perforazione, ATT Fis +3%, ATT Fis +10%, ATT Mag +5%, ATT Mag +10%Induttore E", "Riserva Protect"))
    zoolab.set_fiend_property("rewards", "DEINONYCHUS", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Lentezza, DIF Fis +3%"))
    zoolab.set_fiend_property("rewards", "DEMOMONOLIX", ("Perforazione, ATT Pietra, ATT Pietra +", "DIF Pietra, DIF Pietra +, Incontri 0"))
    zoolab.set_fiend_property("rewards", "DESFLOT", ("Perforaz., Fuocattac., Tuonattac., Acquattac.,Gelattac., ATT Fis +3%, ATT Mag +3%, Induttore V", "DIF Caos, DIF Caos +, MP+10%"))
    zoolab.set_fiend_property("rewards", "DINGO", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "ATT Mutismo, ATT Sonno, DIF Mag +3%"))
    zoolab.set_fiend_property("rewards", "ECHENEIS", ("Perforazione, ATT Fis +3%, ATT Fis +5%", "DIF Zombie, DIF Fis +5%, DIFFis +10%"))
    zoolab.set_fiend_property("rewards", "EFREY", ("Perforazione, ATT Pietra", "DIF Pietra"))
    zoolab.set_fiend_property("rewards", "EFREY OLTANA", ("Perforazione, ATT Pietra", "DIF Pietra"))
    zoolab.set_fiend_property("rewards", "ELEMENTO BIANCO", ("Perforazione, Gelattacco, Induttore M", "Gelo -50%, Immunogelo"))
    zoolab.set_fiend_property("rewards", "ELEMENTO BLU", ("Perforazione, Acquattacco, Induttore M", "Acqua -50%, Immunoacqua"))
    zoolab.set_fiend_property("rewards", "ELEMENTO DORATO", ("Perforazione, Tuonattacco, Induttore M", "Tuono -50%, Immunotuono"))
    zoolab.set_fiend_property("rewards", "ELEMENTO GIALLO", ("Perforazione, Tuonattacco, Induttore M", "Tuono -50%"))
    zoolab.set_fiend_property("rewards", "ELEMENTO NERO", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore M", "Fuoco -50%, Immunofuoco, Tuono -50%,Immunotuono, Immunoacqua, Gelo -50%, Immunogelo"))
    zoolab.set_fiend_property("rewards", "ELEMENTO ROSSO", ("Perforazione, Fuocattacco, Induttore M", "Fuoco -50%, Immunofuoco"))
    zoolab.set_fiend_property("rewards", "ELEMENTO SCURO", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore M", "Fuoco -50%, Tuono -50%, Immunotuono, Acqua-50%, Gelo -50%"))
    zoolab.set_fiend_property("rewards", "EPEJ", ("Perforazione, ATT Fis +5%, ATT Mag +5%,Riserva Turbo", "DIF Fis +5%"))
    zoolab.set_fiend_property("rewards", "ESPRIT", ("Perforazione, ATT Sonno, ATT Sonno +", "DIF Sonno +, DIF Mag +20%"))
    zoolab.set_fiend_property("rewards", "EXORAY", ("Perforazione, ATT Sonno, ATT Fis +5%, ATT Mag+5%", "DIF Sonno, MP +10%"))
    zoolab.set_fiend_property("rewards", "FANTASMA", ("Perforazione, ATT Mag +5%, ATT Mag +10%,Induttore M", "DIF Morte, MP +10%, Incontri 0"))
    zoolab.set_fiend_property("rewards", "FUNGONGO", ("Perforazione, ATT Sonno, ATT Fis +3%, ATT Mag+3%", "DIF Sonno, MP +5%"))
    zoolab.set_fiend_property("rewards", "GALKIMASELA", ("Perforazione,Tuonattacco, Induttore M", "Tuono -50%, Immunotuono"))
    zoolab.set_fiend_property("rewards", "GANDHARVA", ("Perforazione, Tuonattacco, Induttore M", "Tuono -50%, DIF Mag +3%"))
    zoolab.set_fiend_property("rewards", "GARM", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Mutismo, DIF Sonno, DIF Fis +3%"))
    zoolab.set_fiend_property("rewards", "GARUDA", ("Perforazione, ATT Blind, ATTFis +3%, ATT Mag +3%", "DIF Blind"))
    zoolab.set_fiend_property("rewards", "GARUDA", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "DIF Blind"))
    zoolab.set_fiend_property("rewards", "GARUDA", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "DIF Blind"))
    zoolab.set_fiend_property("rewards", "GRANAD", ("Perforazione,Fuocattacco, Induttore M", "Fuoco -50%, Immunofuoco"))
    zoolab.set_fiend_property("rewards", "GRAT", ("Perforazione, ATT Veleno, ATT Fis +5%, ATT Mag+5%", "DIF Veleno, HP +5%, HP +10%"))
    zoolab.set_fiend_property("rewards", "GRENDEL", ("Perforazione, Fuocattacco, ATT Mutismo,Induttore A", "HP +10%"))
    zoolab.set_fiend_property("rewards", "GUARDIA GUADO", ("Spot, Perforazione, ATT Fis +3%, ATT Fis +5%,ATT Mag +3%, ATT Mag +5%", "HP +5%, MP +5%, DIF Mag +3%"))
    zoolab.set_fiend_property("rewards", "GUARDIA GUADO", ("Spot, Perforazione, ATT Fis +3%, ATT Fis +5%,ATT Mag +3%, ATT Mag +5%", "HP +5%, MP +5%, DIF Mag +3%"))
    zoolab.set_fiend_property("rewards", "GUARDIA GUADO", ("Spot, Perforazione, ATT Fis +3%, ATT Fis +5%,ATT Mag +3%, ATT Mag +5%", "HP +5%, MP +5%, DIF Mag +3%"))
    zoolab.set_fiend_property("rewards", "HARUMA", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Berserk, DIF Berserk +"))
    zoolab.set_fiend_property("rewards", "HEG", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Lentezza"))
    zoolab.set_fiend_property("rewards", "HOGA", ("Perforazione, ATT Fis +5%, ATT Mag +5%,Contrattacco", "Riserva Haste, HP +10%"))
    zoolab.set_fiend_property("rewards", "IAGUARO", ("Perforazione, ATT Morte +, ATT Fis +5%, ATTMag +5%, ATT Mag +10%", "DIF Morte, DIF Fis +10%, DIFMag +10%"))
    zoolab.set_fiend_property("rewards", "IPIRIA", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Lentezza, DIF Fis +3%"))
    zoolab.set_fiend_property("rewards", "JOSGUEIN", ("Incontri 0", "Autoreflex"))
    zoolab.set_fiend_property("rewards", "KIMAHRI", ("Spot, Perforazione", "DIF Fis +5%"))
    zoolab.set_fiend_property("rewards", "KING BEHEMOTH", ("Perforazione, ATT Zombie, Riserva Turbo", "Riserva Shell, Riserva Protect, Riserva Reflex"))
    zoolab.set_fiend_property("rewards", "KUSARIK", ("Perforazione, Fuocattacco, Tuonattacco, Acquattacco, Gelattacco,Induttore E", "DIF Lentezza, DIF Fis +5%"))
    zoolab.set_fiend_property("rewards", "KUSHIPOS", ("Perforazione, ATT Fis +3%, ATT Mag +3%, Riserva Turbo", "DIF Fis +5%"))
    zoolab.set_fiend_property("rewards", "KUSHIPOS", ("Perforazione, Fuocattacco, Induttore E", "Immunofuoco, Mangiafuoco"))
    zoolab.set_fiend_property("rewards", "KYACTUS", ("Perforazione, Priorità", "Maratona x HP, Maratona x MP, HP +10%"))
    zoolab.set_fiend_property("rewards", "KYACTUS?", ("Perforazione, Priorità, ATT Fis +5%, ATT Mag +5%", "Maratona x HP, Maratona x MP, HP +5%"))
    zoolab.set_fiend_property("rewards", "LANCIATORE ALBHED", ("Perforazione, Tuonattacco", "DIF Fis +3%"))
    zoolab.set_fiend_property("rewards", "LARVA", ("Perforazione, Tuonattacco", "Tuono -50%"))
    zoolab.set_fiend_property("rewards", "LESMATHOR", ("Perforaz.,Fuocattac., Tuonattac., Acquattac., Gelattac., Induttore V, ATT Fis+3%, ATT Mag +3%", "DIF Veleno, MP +5%"))
    zoolab.set_fiend_property("rewards", "LUMBRIKUS", ("Perforazione, ATT Lentezza, ATT Lentezza +,ATT Fis +5%, ATT Mag +5%", "HP +10%, Autopozione"))
    zoolab.set_fiend_property("rewards", "LUPO DEL DESERTO", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Mutismo, DIF Sonno, DIF Mag +3%"))
    zoolab.set_fiend_property("rewards", "LUPO DELLE NEVI", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Mutismo, DIF Sonno, DIF Mag +3%"))
    zoolab.set_fiend_property("rewards", "MAFUT", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Berserk, DIF Fis +5%"))
    zoolab.set_fiend_property("rewards", "MAL BERNARDO", ("Perforaz.,Fuocattac., Tuonattac., Acquattac., Gelattac., Induttore E, ATT Fis+3%, ATT Mag +3%", "DIF Mutismo, DIF Sonno"))
    zoolab.set_fiend_property("rewards", "MANDRAGORA", ("Perforazione, ATT Veleno, ATT Fis +5%, ATT Mag+5%", "DIF Blind, DIFMutismo, DIF Sonno, DIF Veleno, DIF Pietra, DIF Caos, DIF Berserk"))
    zoolab.set_fiend_property("rewards", "MANGIACHOCOBO", ("Spot, Perforazione, ATT Fis +5%, ATT Fis +10%,ATT Mag +5%, ATT Mag +10%", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%"))
    zoolab.set_fiend_property("rewards", "MASTER IAGUARO", ("Perforazione,ATT Morte, ATT Morte +, ATT Fis +5%, ATT Mag +5%, ATT Mag +10%", "DIF Morte, DIF Morte +, DIF Meledizione +, DIFFis +10%, DIF Mag +10%"))
    zoolab.set_fiend_property("rewards", "MASTRO TOMBERRY", ("Perforazione, ATT Morte +, ATT Lentezza +", "DIF Morte, DIF Morte +"))
    zoolab.set_fiend_property("rewards", "MECHY", ("Perforazione, ATT Fis +5%, ATT Mag +5%,Riserva Turbo", "DIF Fis +10%, DIF Fis +20%"))
    zoolab.set_fiend_property("rewards", "MERYUJIN", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Lentezza, DIF Fis +3%"))
    zoolab.set_fiend_property("rewards", "MIHEN PHANG", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Mutismo, DIF Sonno"))
    zoolab.set_fiend_property("rewards", "MOLBORO", ("Perforazione, ATT Blind, ATT Mutismo, ATTSonno, ATT Veleno", "DIF Blind, DIF Mutismo, DIF Sonno, DIF Veleno,DIF Pietra, DIF Caos, DIF Berserk"))
    zoolab.set_fiend_property("rewards", "MOLBORO IL GRANDE", ("Perforazione, ATT Blind, ATT Mutismo, ATTSonno, ATT Veleno", "DIF Blind, DIF Mutismo, DIF Sonno, DIF Veleno,DIF Pietra, DIF Caos, DIF Berserk"))
    zoolab.set_fiend_property("rewards", "MULFUS", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Berserk, DIF Fis +5%"))
    zoolab.set_fiend_property("rewards", "MUSHUHUSHU", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Lentezza, HP +10%"))
    zoolab.set_fiend_property("rewards", "NEBIROS", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Veleno"))
    zoolab.set_fiend_property("rewards", "NEO SEYMOUR", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva Shell"))
    zoolab.set_fiend_property("rewards", "OCCHIO DIABOLICO", ("Perforaz.,Fuocattac., Tuonattac., Acquattac., Gelattac., ATT Fis +3%, ATT Mag+3%, Induttore V", "DIF Caos, MP +10%"))
    zoolab.set_fiend_property("rewards", "OCCHIO DIABOLICO", ("Perforaz.,Fuocattac., Tuonattac., Acquattac., Gelattac., ATT Fis +3%, ATT Mag+3%, Induttore V", "DIF Caos, MP +10%"))
    zoolab.set_fiend_property("rewards", "OCCHIO FLUTTUANTE", ("Perforaz.,Fuocattac., Tuonattac., Acquattac., Gelattac., ATT Fis +3%, ATT Mag+3%, Induttore V", "DIF Caos, MP +10%"))
    zoolab.set_fiend_property("rewards", "OCCHIO MALVAGIO", ("Perforaz.,Fuocattac., Tuonattac., Acquattac., Gelattac., ATT Fis +3%, ATT Mag+3%, Induttore V", "DIF Caos, MP +10%"))
    zoolab.set_fiend_property("rewards", "OCHU", ("Perforazione, ATT Veleno, ATT Fis +5%, ATT Mag+5%", "DIF Blind, DIF Mutismo, DIF Sonno, DIF Veleno,DIF Pietra, DIF Caos, DIF Berserk"))
    zoolab.set_fiend_property("rewards", "OCHU SMARRITO", ("Perforazione, ATT Veleno, ATT Fis +5%, ATT Mag+5%", "DIF Blind, DIF Mutismo, DIF Sonno, DIF Veleno,DIF Pietra, DIF Caos, DIF Berserk"))
    zoolab.set_fiend_property("rewards", "OCTOPUS", ("Perforazione, Acquattacco, ATT Fis +5%, ATTMag +5%", "Acqua -50%, HP +5%"))
    zoolab.set_fiend_property("rewards", "OMEGA WEAPON", ("Triturbo", "HP Apeiron"))
    zoolab.set_fiend_property("rewards", "PALUDOMAFUT", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Berserk, DIF Fis +5%"))
    zoolab.set_fiend_property("rewards", "PHLEGYAS", ("Perforazione, ATT Fis +5%, ATT Mag +5%", "MP +10%, Autopanacea"))
    zoolab.set_fiend_property("rewards", "PIROS", ("Perforazione, Fuocattacco, Induttore E", "Fuoco -50%"))
    zoolab.set_fiend_property("rewards", "PIROS", ("Perforazione, Fuocattacco, Induttore E", "Fuoco -50%"))
    zoolab.set_fiend_property("rewards", "PORTIERE ALBHED", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva Parafire, Riserva Parathund, RiservaParaidro, Riserva Parabliz"))
    zoolab.set_fiend_property("rewards", "RAMASHUT", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Lentezza, HP +5%"))
    zoolab.set_fiend_property("rewards", "RAPTOR", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Lentezza, DIF Fis +3%"))
    zoolab.set_fiend_property("rewards", "RARTH", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Berserk, DIF Fis +3%"))
    zoolab.set_fiend_property("rewards", "REMORA", ("Perforazione, ATT Fis +3%, ATT Fis +5%", "DIF Zombie, DIF Fis +5%"))
    zoolab.set_fiend_property("rewards", "RICEVITORE ALBHED", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva Parafire, Riserva Parathund, RiservaParaidro, Riserva Parabliz"))
    zoolab.set_fiend_property("rewards", "SAHAGIN", ("Perforazione, Acquattacco, AFF Fis +3%, ATTMag +3%", "Acqua -50%, HP +5%"))
    zoolab.set_fiend_property("rewards", "SAHAGIN", ("Perforazione, Acquattacco, AFF Fis +3%, ATTMag +3%", "Acqua -50%, HP +5%"))
    zoolab.set_fiend_property("rewards", "SCAGLIA EKYU", ("Perforazione, Acquattacco", "Acqua -50%"))
    zoolab.set_fiend_property("rewards", "SCAGLIA GHY", ("Perforazione, ATT Sonno +", "DIF Sonno +"))
    zoolab.set_fiend_property("rewards", "SCAGLIA GHY", ("Perforazione, ATT Sonno +", "DIF Sonno +"))
    zoolab.set_fiend_property("rewards", "SCAGLIA GUNAI", ("Perforazione, ATT Zombie +", "DIF Zombie +"))
    zoolab.set_fiend_property("rewards", "SCAGLIA GUNO", ("Perforazione, ATT Blind", "DIF Blind"))
    zoolab.set_fiend_property("rewards", "SCOOR", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Mutismo, DIF Sonno"))
    zoolab.set_fiend_property("rewards", "SEYMOUR", ("Perforazione, ATT Mutismo +", "DIF Mutismo +"))
    zoolab.set_fiend_property("rewards", "SEYMOUR BETA", ("Perforazione, ATT Blind +", "DIF Blind +"))
    zoolab.set_fiend_property("rewards", "SEYMOUR OMEGA", ("Perforazione, ATT Mag +20%", "Riserva Shell, Riserva Protect, Riserva Haste"))
    zoolab.set_fiend_property("rewards", "SFEROGESTORE", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%"))
    zoolab.set_fiend_property("rewards", "SHRED", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Berserk"))
    zoolab.set_fiend_property("rewards", "SHUMELKE", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Lentezza, DIF Fis +5%"))
    zoolab.set_fiend_property("rewards", "SHUMELKE KRYPT", ("Perforaz.,Fuocat., Tuonat., Acquat., Gelat., ATT Fis +3%, ATT Fis +5%, ATT Mag+3%, ATT Mag +5%", "DIF Lentezza, DIF Fis +5%"))
    zoolab.set_fiend_property("rewards", "SIGILLO ALBHED", ("Perforazione, Tuonattacco", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%"))
    zoolab.set_fiend_property("rewards", "SIMURGH", ("Spot, Perforazione, Induttore V", "DIF Blind, DIF Mag +3%"))
    zoolab.set_fiend_property("rewards", "SIN", ("Perforazione, Gelattacco", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%"))
    zoolab.set_fiend_property("rewards", "SIN", ("Perforazione, ATT Lentezza +", "DIF Lentezza +"))
    zoolab.set_fiend_property("rewards", "SIN", ("Perforazione, ATT Blind +, ATT Mutismo +, ATTSonno +, ATT Lentezza +", "DIF Mutismo +"))
    zoolab.set_fiend_property("rewards", "SON", ("Perforazione,ATT Sonno, ATT Fis +3%, ATT Fis +5%, ATT Mag +3%, ATT Mag +5%", "DIF Sonno, MP +5%"))
    zoolab.set_fiend_property("rewards", "SPLASHER", ("Perforazione, Acquattacco, ATT Fis +5%, ATTMag +5%", "HP +5%, DIF Fis +3%"))
    zoolab.set_fiend_property("rewards", "TEMPLARE", ("Perforazione, ATT Fis +5%, Contramagia", "DIF Morte, DIF Mag +3%"))
    zoolab.set_fiend_property("rewards", "TEMPLARE REDIVIVO", ("Perforazione, ATT Fis +5%, Contramagia", "DIF Zombie, DIF Mag +3%"))
    zoolab.set_fiend_property("rewards", "TESTA", ("Perforazione, Fuocattacco, Tuonattacco,Acquatacco, Gelattacco", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%"))
    zoolab.set_fiend_property("rewards", "THYTAN", ("Perforazione, ATT Fis +5%, ATT Fis +10%, ATTMag +5%, ATT Mag +10%", "Riserva Rigene, HP +5%, HP +10%"))
    zoolab.set_fiend_property("rewards", "TOMBERRY", ("Perforazione, ATT Morte, ATT Lentezza", "DIF Morte"))
    zoolab.set_fiend_property("rewards", "ULTIMA WEAPON", ("Biturbo", "MP apeiron"))
    zoolab.set_fiend_property("rewards", "ULTRA MIGHT (SPADA STELLA)", ("Perforazione, ATT Fis +10%, ATT Mag +10%", "Riserva Rigene, HP +10%"))
    zoolab.set_fiend_property("rewards", "ULTRA MIGHT (SPADA NORMALE)", ("Perforazione, ATT Fis +10%, ATT Mag +10%", "Riserva Rigene, HP +10%"))
    zoolab.set_fiend_property("rewards", "UNITÀ 97", ("Perforazione, ATT Fis +5%, ATT Mag +5%", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%"))
    zoolab.set_fiend_property("rewards", "UNITÀ 99", ("Fuocat.,Tuonat., Acquat., Gelat., ATT Fis +3%, ATT Fis +5%, ATT Mag +3%, ATTMag +5%, Induttore V", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%"))
    zoolab.set_fiend_property("rewards", "UNITÀ BLINDATA 11", ("Perforazione, ATT Fis +5%, ATT Mag +5%", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%"))
    zoolab.set_fiend_property("rewards", "UNITÀ BLINDATA 63", ("Perforazione, ATT Fis +3%, ATT Fis +5%, ATTMag +3%, ATT Mag +5%", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%"))
    zoolab.set_fiend_property("rewards", "VARAHA", ("Perforazione, Fuocattacco, ATT Mutismo,Induttore A", "HP +10%"))
    zoolab.set_fiend_property("rewards", "VARNA", ("Perforazione, ATT Mag +10%, Biturbo", "Riserva Shell, DIF Mag +10%"))
    zoolab.set_fiend_property("rewards", "VESPA", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Veleno, MP +10%"))
    zoolab.set_fiend_property("rewards", "VIHUR", ("Perforazione, Gelattacco", "DIF Lentezza, HP +5%"))
    zoolab.set_fiend_property("rewards", "VIVRE", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Lentezza, HP +5%"))
    zoolab.set_fiend_property("rewards", "WENDIGO", ("Perforazione, Contrattacco", "Riserva Haste, HP +10%"))
    zoolab.set_fiend_property("rewards", "YENKE RONSO", ("Perforazione", "MP +20%"))
    zoolab.set_fiend_property("rewards", "YOWIE", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Lentezza"))
    zoolab.set_fiend_property("rewards", "YUNALESCA", ("Perforazione, ATT Zombie +", "DIF Zombie +"))
    zoolab.set_fiend_property("rewards", "ZAURAS", ("Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Lentezza, DIF Lentezza +"))
    zoolab.set_fiend_property("rewards", "ZUU", ("Perforazione, ATT Blind, ATT Fis +3%, ATT Mag+3%", "DIF Blind"))
    zoolab.set_fiend_property("rewards", "ZUU", ("Perforazione, ATT Blind, ATT Fis +5%, ATT Mag+5%", "DIF Blind"))

    zoolab.set_fiend_property("stats", "ADAMANTHART", ("54400", "40", "12500", "2200", "Energosfera x2", ["Acqua Curativa x1", "Nettare Energetico"], "-"))
    zoolab.set_fiend_property("stats", "ALCIONE", ("430", "42", "310", "240", "Velocisfera x1, Albhedina x1", ["Lacrimogeno x1", "Lacrimogeno x2"], "-"))
    zoolab.set_fiend_property("stats", "ALYADIN", ("22222", "3500", "3100", "1070", "Magicosfera x1", ["Ombra d'Oltremondo", "Vento d'Oltremondo"], "Sentenza"))
    zoolab.set_fiend_property("stats", "ALYMAN", ("2800", "400", "2200", "750", "Velocisfera x1", ["Stricnina x2", "Stricnina x3"], "-"))
    zoolab.set_fiend_property("stats", "ANACONDAR", ("5800", "70", "1380", "750", "Energosfera x1", ["Granata Fossile x1", "Granata Fossile x2"], "Fossilspiro"))
    zoolab.set_fiend_property("stats", "ANELLIDUS", ("4500", "100", "2000", "1000", "Abilitosfera x2", ["Neromagilite x1", "Fluido Energetico x2"], "-"))
    zoolab.set_fiend_property("stats", "ANIMA", ("18000", "50", "2500", "3000", "Abilitosfera x1", ["Mina Tacet x3", "Ombra d'Oltremondo x1"], "-"))
    zoolab.set_fiend_property("stats", "APE KILLER", ("110", "5", "9", "23", "Velocisfera x1", ["Antidoto x1", "Zanna velenosa x1"], "-"))
    zoolab.set_fiend_property("stats", "AQUELOUS", ("5100", "85", "730", "420", "Energosfera x1", ["Idromagilite x2", "Fluido Rigenerante x1"], "-"))
    zoolab.set_fiend_property("stats", "AROJ", ("200", "220", "92", "144", "Magicosfera x1", ["Razzo elettrico x1", "Razzo fulminante x1"], "-"))
    zoolab.set_fiend_property("stats", "ASHOOR", ("17000", "5", "1860", "730", "Energosfera x1", ["Fluido vitale x1", "Fluido vitale x2"], "-"))
    zoolab.set_fiend_property("stats", "AUTOARMATURA", ("8700", "1", "950", "880", "Coda di fenice x1", ["Albhedina x2", "Albhedina x3"], "-"))
    zoolab.set_fiend_property("stats", "AUTOARTIGLIERE", ("2800", "1", "540", "800", "Granpozione x2", ["Albhedina x1", "Albhedina x2"], "-"))
    zoolab.set_fiend_property("stats", "AUTOCACCIATORE", ("5500", "1", "420", "673", "Coda di fenice x1", ["Albhedina x1", "Albhedina x2"], "-"))
    zoolab.set_fiend_property("stats", "AUTOCOMMANDER", ("3700", "1", "830", "530", "Granpozione x1", ["Granata x2", "Blindogranata x2"], "-"))
    zoolab.set_fiend_property("stats", "AUTOGUARDIANO", ("1280", "1", "310", "600", "Granpozione x1", ["Granata fossile x2", "Granata fossile x3"], "-"))
    zoolab.set_fiend_property("stats", "AUTOSCOUT", ("2750", "1", "480", "384", "Granpozione x1", ["Granata fossile x3", "Granata fossile x3"], "-"))
    zoolab.set_fiend_property("stats", "BALSAMIKO", ("780", "15", "20", "48", "Magicosfera x1", ["Antidoto x1", "Panacea x1"], "Cerbottana"))
    zoolab.set_fiend_property("stats", "BALSAMIKO GRASSO", ("12750", "3", "540", "336", "Magicosfera x1", ["Panacea x2", "Stricnina x10"], "Cerbottana"))
    zoolab.set_fiend_property("stats", "BARBATOS", ("95000", "480", "17500", "1550", "Energosfera x1", ["Cortina stellare x1", "Sacromagilite x1"], "-"))
    zoolab.set_fiend_property("stats", "BASILISK", ("2025", "20", "140", "125", "Abilitosfera x1", ["Granata fossile x1", "Granata fossile x1"], "Fossilspiro"))
    zoolab.set_fiend_property("stats", "BEHEMOTH", ("23000", "480", "6540", "1350", "Energosfera x1", ["Etere x1", "Nettare energetico x1"], "Difesa totale"))
    zoolab.set_fiend_property("stats", "BIKORNO", ("1875", "18", "42", "105", "Abilitosfera x1", ["Pozione x1", "Granpozione x1"], "Pirosbolle"))
    zoolab.set_fiend_property("stats", "BIKORNO", ("3795", "22", "820", "520", "Abilitosfera x1", ["Granpozione x1", "Megapozione x1"], "Pirosbolle"))
    zoolab.set_fiend_property("stats", "BIRAN RONSO", ("Variabile", "200", "4500", "1500", "Gamberosfera x1", ["Passosfera Lv 3 x2", "Passosfera Lv 3 x3"], "4 Nemitec diverse"))
    zoolab.set_fiend_property("stats", "BOTTE MAGICA", ("999999", "999", "0", "0", "-", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "BRACCIO", ("800", "1", "37", "300", "-", ["Pozione x1", "Pozione x1"], "-"))
    zoolab.set_fiend_property("stats", "BRACCIO DX DI SIN", ("65000", "999", "17000", "10000", "Passosfera Lv 3 x1", ["Extrapozione x1", "Eliomagilite x1"], "-"))
    zoolab.set_fiend_property("stats", "BRACCIO SX DI SIN", ("65000", "999", "16000", "10000", "Accapisfera x1", ["Megapozione x1", "Examagilite x1"], "-"))
    zoolab.set_fiend_property("stats", "BUDINO D'ACQUA", ("315", "30", "2", "18", "Magicosfera x1", ["Squame di pesce x1", "Squame di drago x1"], "-"))
    zoolab.set_fiend_property("stats", "BUDINO D'ACQUA", ("2025", "1", "240", "340", "Magicosfera x1", ["Squame di pesce x2", "Squame di drago x2"], "-"))
    zoolab.set_fiend_property("stats", "BUDINO DI FIAMME", ("1500", "200", "480", "448", "Magicosfera x1", ["Magmagilite x1", "Magmagilite x2"], "-"))
    zoolab.set_fiend_property("stats", "BUDINO DI GHIACCIO", ("1350", "160", "300", "188", "Magicosfera x1", ["Vento antartico x1", "Vento antartico x2"], "-"))
    zoolab.set_fiend_property("stats", "BUDINO DI NEVE", ("600", "120", "48", "93", "Magicosfera x1", ["Vento antartico x1", "Vento antartico x2"], "-"))
    zoolab.set_fiend_property("stats", "BUDINO DI TUONO", ("450", "50", "24", "50", "Magicosfera x1", ["Razzo elettrico x1", "Razzo elettrico x2"], "-"))
    zoolab.set_fiend_property("stats", "BUDINO OSCURO", ("12800", "250", "3750", "1080", "Magicosfera x1", ["Cortina stellare x1", "Cortina stellare x2"], "Vento bianco"))
    zoolab.set_fiend_property("stats", "BUEL", ("230", "250", "92", "132", "Velocisfera x1", ["Granpozione x1", "Stricnina x1"], "-"))
    zoolab.set_fiend_property("stats", "BUNYIPS", ("400", "15", "48", "97", "Energosfera x1", ["Granpozione x1", "Hypellina x1"], "-"))
    zoolab.set_fiend_property("stats", "CANNONIERE ALBHED", ("16000", "1", "4400", "7000", "Elisir x1", ["Cortina lunare x1", "Cortina lunare x2"], "-"))
    zoolab.set_fiend_property("stats", "CAPITAN SAHAGIN", ("170", "5", "2", "20", "Energosfera x1", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "CHIMERA", ("5250", "130", "1220", "970", "Abilitosfera x1", ["Vento Antartico x1", "Razzo Fulminante x1"], "Idrorespiro"))
    zoolab.set_fiend_property("stats", "CHIMERA", ("9000", "200", "2000", "980", "Abilitosfera x1", ["Vento Antartico x3", "Razzo Fulminante x3"], "Idrorespiro"))
    zoolab.set_fiend_property("stats", "CHIMERA BRAIN", ("9800", "250", "1200", "1000", "Abilitosfera x1", ["Criomagilite x1", "Elettromagilite x2"], "Idrorespiro"))
    zoolab.set_fiend_property("stats", "CONDOR", ("95", "15", "2", "12", "Velocisfera x1", ["Coda di Fenice x1", "Lacrimogeno x2"], "-"))
    zoolab.set_fiend_property("stats", "CUSTODE CELESTE", ("40000", "256", "11000", "6500", "Gamberosfera x1", ["Turboetere x1", "Turboetere x2"], "-"))
    zoolab.set_fiend_property("stats", "CUSTODE DEL LIMBO", ("52000", "500", "12000", "7000", "Passosfera Lv 4 x1", ["Etere x1", "Turboetere x1"], "-"))
    zoolab.set_fiend_property("stats", "DEDALARVA", ("2222", "1111", "1850", "620", "Abilitosfera x1", ["Squama di pesce x1", "Squama di pesce x2"], "-"))
    zoolab.set_fiend_property("stats", "DEFENDER", ("12000", "1", "2700", "1300", "Energosfera x2", ["Cortina Lunare x1", "Cortina Lunare x2"], "-"))
    zoolab.set_fiend_property("stats", "DEFENDER ZERO", ("42300", "1", "6000", "2400", "Passosfera Lv 2 x1", ["Cortina lunare x2", "Cortina lunare x2"], "-"))
    zoolab.set_fiend_property("stats", "DEFENSOR", ("64000", "1", "6600", "3500", "Passosfera Lv 2 x2", ["Cortina Lunare x4", "Cortina Lunare x4"], "-"))
    zoolab.set_fiend_property("stats", "DEINONYCHUS", ("140", "25", "9", "27", "Velocisfera x1", ["Ago dorato x1", "Granata fossile x1"], "-"))
    zoolab.set_fiend_property("stats", "DEMOMONOLIX", ("45000", "9999", "11000", "1470", "Magicosfera x2", ["Granata fossile x2", "Granata fossile x2"], "-"))
    zoolab.set_fiend_property("stats", "DESFLOT", ("6700", "520", "7100", "1265", "Magicosfera x2", ["Stricnina x4", "Stricnina x5"], "-"))
    zoolab.set_fiend_property("stats", "DINGO", ("125", "10", "2", "15", "Energosfera x1", ["Pozione x1", "Melatonina x1"], "-"))
    zoolab.set_fiend_property("stats", "ECHENEIS", ("10000", "35", "600", "330", "Magicosfera x1", ["Idromagilite x2", "Idromagilite x3"], "-"))
    zoolab.set_fiend_property("stats", "EFREY", ("32000", "500", "5400", "2600", "Mnerosfera x1", ["Idromagilite x1", "Idromagilite x2"], "-"))
    zoolab.set_fiend_property("stats", "EFREY OLTANA", ("16384", "200", "5800", "3000", "Mnerosfera x1", ["Idromagilite x2", "Fluido rigenerante x1"], "-"))
    zoolab.set_fiend_property("stats", "ELEMENTO BIANCO", ("390", "120", "20", "48", "Magicosfera x1", ["Vento artico x1", "Vento artico x2"], "-"))
    zoolab.set_fiend_property("stats", "ELEMENTO BLU", ("1500", "220", "240", "180", "Magicosfera x1", ["Squame di pesce x2", "Squame di pesce x3"], "-"))
    zoolab.set_fiend_property("stats", "ELEMENTO DORATO", ("1200", "180", "92", "107", "Magicosfera x1", ["Razzo elettrico x1", "Razzo elettrico x2"], "-"))
    zoolab.set_fiend_property("stats", "ELEMENTO GIALLO", ("300", "100", "9", "33", "Magicosfera x1", ["Razzo elettrico x1", "Razzo fulminante x1"], "-"))
    zoolab.set_fiend_property("stats", "ELEMENTO NERO", ("7600", "500", "3150", "1040", "Magicosfera x1", ["Granpozione x1", "Eliomagilite x1"], "-"))
    zoolab.set_fiend_property("stats", "ELEMENTO ROSSO", ("450", "130", "32", "55", "Magicosfera x1", ["Scheggia di Piros x1", "Scheggia di Piros x2"], "-"))
    zoolab.set_fiend_property("stats", "ELEMENTO SCURO", ("1800", "280", "810", "520", "Magicosfera x1", ["Spina iperica x1", "Spina iperica x2"], ""))
    zoolab.set_fiend_property("stats", "EONE DI BRASKA", ("60000", "100", "0", "0", "-", ["Turboetere x1", "Elisir x1"], "-"))
    zoolab.set_fiend_property("stats", "EONE DI BRASKA", ("120000", "100", "0", "0", "-", ["Turboetere x1", "Elisir x1"], "-"))
    zoolab.set_fiend_property("stats", "EPEJ", ("8700", "20", "970", "950", "Abilitosfera x2", ["Granpozione x1", "Granpozione x2"], "-"))
    zoolab.set_fiend_property("stats", "ESPRIT", ("10000", "700", "4300", "1300", "Magicosfera x1", ["Fluido energetico x1", "Fluido energetico x2"], "Vento bianco"))
    zoolab.set_fiend_property("stats", "EXORAY", ("7400", "300", "2400", "840", "Magicosfera x1", ["Mina Tacet x3", "Etere x1"], "-"))
    zoolab.set_fiend_property("stats", "FANTASMA", ("9999", "350", "1450", "810", "Magicosfera x1", ["Coda di fenice x1", "Ombra d'Oltremondo x1"], "Sentenza"))
    zoolab.set_fiend_property("stats", "FUNGONGO", ("540", "60", "44", "42", "Magicosfera x1", ["Mina Tacet x1", "Etere x1"], "-"))
    zoolab.set_fiend_property("stats", "GALKIMASELA", ("880", "300", "770", "610", "Magicosfera x1", ["Elettromagilite x1", "Elettromagilite x2"], "-"))
    zoolab.set_fiend_property("stats", "GANDHARVA", ("148", "160", "32", "62", "Magicosfera x1", ["Razzo elettrico x1", "Razzo elettrico x2"], "-"))
    zoolab.set_fiend_property("stats", "GARM", ("240", "35", "48", "88", "Energosfera x1", ["Granpozione x1", "Melatonina x1"], "-"))
    zoolab.set_fiend_property("stats", "GARUDA", ("1400", "50", "8", "30", "Energosfera x1", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "GARUDA", ("1800", "10", "28", "0", "Energosfera x1", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "GARUDA", ("4000", "50", "170", "140", "Energosfera x1", ["Lacrimogeno x1", "Lacrimogeno x1"], "-"))
    zoolab.set_fiend_property("stats", "GRANAD", ("7500", "63", "1350", "540", "Energosfera x1", ["Magmagilite x2", "Magmagilite x3"], "Kamikaze"))
    zoolab.set_fiend_property("stats", "GRAT", ("4000", "25", "980", "520", "Magicosfera x1", ["Antidoto x4", "Panacea x3"], "Cerbottana"))
    zoolab.set_fiend_property("stats", "GRENDEL", ("9500", "62", "2600", "730", "Abilitosfera x1", ["Granpozione x1", "Megapozione x1"], "Pirosbolle"))
    zoolab.set_fiend_property("stats", "GUARDIA GUADO", ("2000", "10", "290", "300", "Abilitosfera x1", ["Granpozione x1", "Etere x1"], "-"))
    zoolab.set_fiend_property("stats", "GUARDIA GUADO", ("1200", "330", "290", "480", "Abilitosfera x1", ["Granpozione x1", "Extrapozione x1"], "-"))
    zoolab.set_fiend_property("stats", "GUARDIA GUADO", ("2600", "600", "540", "380", "Abilitosfera x1", ["Granpozione x1", "Extrapozione x2"], "-"))
    zoolab.set_fiend_property("stats", "HARUMA", ("13000", "1", "5300", "1030", "Energosfera x1", ["Hypellina x3", "Neromagilite x2"], "-"))
    zoolab.set_fiend_property("stats", "HEG", ("2000", "46", "810", "602", "Energosfera x1", ["Granpozione x1", "Clessidra d'oro x1"], "-"))
    zoolab.set_fiend_property("stats", "HOGA", ("9400", "3", "1080", "980", "Energosfera x1", ["Fluido energetico x1", "Fluido energetico x2"], "-"))
    zoolab.set_fiend_property("stats", "IAGUARO", ("6000", "480", "1300", "1100", "Magicosfera x1", ["Fluido magico x1", "Fluido magico x1"], "-"))
    zoolab.set_fiend_property("stats", "IPIRIA", ("180", "35", "24", "46", "Velocisfera x1", ["Ago dorato x1", "Granata fossile x1"], "-"))
    zoolab.set_fiend_property("stats", "JOSGUEIN", ("32767", "128", "0", "0", "-", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "JOSGUEIN", ("32767", "128", "4200", "1000", "Energosfera x2", ["Idromagilite x1", "Idromagilite x2"], "-"))
    zoolab.set_fiend_property("stats", "KIMAHRI", ("750", "10", "3", "100", "Abilitosfera x2", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "KING BEHEMOTH", ("67500", "700", "16800", "1850", "Energosfera x1", ["Fluido rigenerante x1", "Duostella x2"], "-"))
    zoolab.set_fiend_property("stats", "KLIK", ("1500", "5", "5", "50", "Abilitosfera x2", ["Granata x1", "Granata x2"], "-"))
    zoolab.set_fiend_property("stats", "KOBUSHI", ("8000", "600", "0", "0", "-", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "KUSARIK", ("445", "31", "92", "111", "Energosfera x1", ["Granpozione x1", "Clessidra d'argento x1"], "-"))
    zoolab.set_fiend_property("stats", "KUSHIPOS", ("2700", "5", "520", "220", "Abilitosfera x1", ["Granpozione x1", "Megapozione x1"], "-"))
    zoolab.set_fiend_property("stats", "KUSHIPOS", ("20000", "180", "3200", "970", "Magicosfera x1", ["Magmagilite x3", "Magmagilite x4"], "Kamikaze"))
    zoolab.set_fiend_property("stats", "KYACTUS", ("800", "1", "8000", "1500", "Velocisfera x2", ["Coda di chocobo x1", "Piuma di chocobo x1"], "-"))
    zoolab.set_fiend_property("stats", "KYACTUS?", ("500", "1", "350", "1500", "Velocisfera x1", ["Coda di chocobo x1", "Coda di chocobo x1"], "-"))
    zoolab.set_fiend_property("stats", "LANCIATORE ALBHED", ("6000", "10", "36", "580", "Elisir x1", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "LARVA", ("1498", "1000", "262", "330", "Abilitosfera x1", ["Cortina lunare x1", "Cortina lunare x2"], "-"))
    zoolab.set_fiend_property("stats", "LESMATHOR", ("200", "10", "40", "62", "Velocisfera x1", ["Antidoto x1", "Zanna velenosa x1"], "-"))
    zoolab.set_fiend_property("stats", "LUMBRIKUS", ("80000", "160", "22000", "2200", "Energosfera x1", ["Fluido energetico x1", "Fluido energetico x1"], "-"))
    zoolab.set_fiend_property("stats", "LUPO DEL DESERTO", ("450", "55", "310", "225", "Energosfera x1, Albhedina x1", ["Melatonina x2", "Melatonina x2"], "-"))
    zoolab.set_fiend_property("stats", "LUPO DELLE NEVI", ("400", "50", "300", "195", "Energosfera x1", ["Melatonina x1", "Melatonina x2"], "-"))
    zoolab.set_fiend_property("stats", "MAFUT", ("710", "25", "300", "172", "Energosfera x1", ["Granpozione x1", "Hypellina x1"], "-"))
    zoolab.set_fiend_property("stats", "MAL BERNARDO", ("1800", "75", "820", "880", "Energosfera x1", ["Onirolina x2", "Onirolina x3"], "-"))
    zoolab.set_fiend_property("stats", "MANDRAGORA", ("31000", "120", "6230", "1200", "Magicosfera x1", ["Panacea x2", "Panacea x3"], "-"))
    zoolab.set_fiend_property("stats", "MANGIACHOCOBO", ("10000", "5", "90", "970", "Passosfera Lv 1 x2", ["Pozione x1", "Pozione x1"], "-"))
    zoolab.set_fiend_property("stats", "MASTER IAGUARO", ("13000", "540", "6500", "2030", "Passosfera Lv 1 x1", ["Ombra d'Oltremondo x2", "Ombra d'Oltremondo x4"], "-"))
    zoolab.set_fiend_property("stats", "MASTRO TOMBERRY", ("48000", "1", "20000", "2400", "Energosfera x1", ["Fluido magico x1", "Tetraelementale x1"], "-"))
    zoolab.set_fiend_property("stats", "MECHY", ("18000", "59", "83000", "1450", "Magicosfera x1", ["Granpozione x2", "Filtro energetico x1"], "-"))
    zoolab.set_fiend_property("stats", "MEKALUNIO", ("4000", "512", "0", "0", "-", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "MERYUJIN", ("265", "65", "92", "108", "Velocisfera x1", ["Ago dorato x1", "Granata fossile x1"], "-"))
    zoolab.set_fiend_property("stats", "MIHEN PHANG", ("160", "20", "20", "33", "Energosfera x1", ["Pozione x1", "Melatonina x1"], "-"))
    zoolab.set_fiend_property("stats", "MIMIK", ("60000", "10", "0", "50000", "-", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "MIMIK", ("40000", "10", "0", "50000", "-", ["-", "-"], ""))
    zoolab.set_fiend_property("stats", "MIMIK", ("40000", "10", "0", "50000", "-", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "MIMIK", ("40000", "10", "0", "50000", "-", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "MOLBORO", ("27000", "1", "2300", "1500", "Magicosfera x2", ["Panacea x1", "Panacea x1"], "Alito fetido"))
    zoolab.set_fiend_property("stats", "MOLBORO IL GRANDE", ("64000", "1", "21000", "1900", "Magicosfera x1", ["Panacea x1", "Nettare magico x1"], "Alito fetido"))
    zoolab.set_fiend_property("stats", "MULFUS", ("580", "20", "240", "165", "Energosfera x1", ["Granpozione x1", "Hypellina x1"], "-"))
    zoolab.set_fiend_property("stats", "MUSHUHUSHU", ("680", "38", "310", "270", "Energosfera x1, Albhedina x1", ["Granpozione x1", "Clessidra d'argento x1"], "-"))
    zoolab.set_fiend_property("stats", "NEBIROS", ("700", "65", "480", "320", "Magicosfera x1", ["Zanna velenosa x1", "Zanna velenosa x2"], "-"))
    zoolab.set_fiend_property("stats", "NEO SEYMOUR", ("36000", "200", "6300", "3500", "Passosfera Lv 2 x2", ["Tetraelementale x2", "Tetraelementale x3"], "-"))
    zoolab.set_fiend_property("stats", "NEOLUNIO", ("4000", "50", "0", "0", "-", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "OCCHIO DIABOLICO", ("310", "300", "300", "205", "Velocisfera x1", ["Granpozione x1", "Stricnina x1"], "-"))
    zoolab.set_fiend_property("stats", "OCCHIO DIABOLICO", ("430", "310", "480", "220", "Velocisfera x1", ["Stricnina x1", "Stricnina x2"], "-"))
    zoolab.set_fiend_property("stats", "OCCHIO FLUTTUANTE", ("140", "200", "21", "44", "Velocisfera x1", ["Erba dell'eco x1", "Stricnina x1"], "-"))
    zoolab.set_fiend_property("stats", "OCCHIO MALVAGIO", ("380", "280", "240", "320", "Velocisfera x1", ["Granpozione x1", "Mina Tacet x2"], "-"))
    zoolab.set_fiend_property("stats", "OCHU", ("7200", "35", "180", "520", "Energosfera x1", ["Panacea x1", "Panacea x2"], "."))
    zoolab.set_fiend_property("stats", "OCHU SMARRITO", ("4649", "39", "40", "420", "Emmepisfera x1", ["Pozione x1", "Pozione x1"], "-"))
    zoolab.set_fiend_property("stats", "OCTOPUS", ("4500", "1", "700", "220", "Magicosfera x1", ["Squame di drago x2", "Idromagilite x2"], "-"))
    zoolab.set_fiend_property("stats", "OMEGA WEAPON", ("999999", "999", "50000", "30000", "Passosfera Lv 4 x3", ["Anima del baro x30", "Anima del baro x30"], "Sunshine"))
    zoolab.set_fiend_property("stats", "PAGODA YU", ("5000", "5000", "0", "0", "-", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "PALUDOMAFUT", ("850", "1", "240", "290", "Energosfera x1", ["Granpozione x1", "Hypellina x1"], "-"))
    zoolab.set_fiend_property("stats", "PHLEGYAS", ("1680", "50", "650", "410", "Energosfera x1", ["Squame di drago x2", "Idromagilite x1"], "-"))
    zoolab.set_fiend_property("stats", "PIRANHA", ("50", "1", "1", "2", "Energosfera x1", ["Granata x1", "Granata x2"], "-"))
    zoolab.set_fiend_property("stats", "PIRANHA X2", ("100", "2", "1", "3", "Magicosfera x1", ["Granata x1", "Granata x2"], "-"))
    zoolab.set_fiend_property("stats", "PIRANHA X3", ("150", "3", "1", "5", "Velocisfera x1", ["Granata x1", "Granata x2"], "-"))
    zoolab.set_fiend_property("stats", "PIROS", ("850", "30", "22", "70", "Energosfera x1", ["Scheggia di Piros x2", "Scheggia di Piros x3"], "Kamikaze"))
    zoolab.set_fiend_property("stats", "PIROS", ("2200", "45", "620", "470", "Energosfera x1", ["Anima di Piros x2", "Anima di Piros x3"], "Kamikaze"))
    zoolab.set_fiend_property("stats", "PORTIERE ALBHED", ("300", "1", "7", "85", "Granpozione x1", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "RAMASHUT", ("275", "21", "32", "72", "Energosfera x1", ["Pozione x1", "Clessidra d'argento x1"], "-"))
    zoolab.set_fiend_property("stats", "RAPTOR", ("200", "45", "32", "48", "Velocisfera x1", ["Ago dorato x1", "Granata fossile x1"], "-"))
    zoolab.set_fiend_property("stats", "RARTH", ("240", "10", "20", "42", "Energosfera x1", ["Pozione x1", "Hypellina x1"], "-"))
    zoolab.set_fiend_property("stats", "REMORA", ("3000", "22", "830", "535", "Magicosfera x1", ["Squame di drago x1", "Squame di drago x2"], "-"))
    zoolab.set_fiend_property("stats", "RICEVITORE ALBHED", ("4000", "10", "660", "2400", "Megafenice x1", ["Pozione x1", "Pozione x1"], "-"))
    zoolab.set_fiend_property("stats", "SAHAGIN", ("100", "5", "0", "0", "-", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "SAHAGIN", ("1380", "20", "200", "180", "Energosfera x1", ["Squame di pesce x2", "Squame di drago x2"], "-"))
    zoolab.set_fiend_property("stats", "SAHAGIN", ("380", "20", "460", "200", "Energosfera x1", ["Squame di pesce x1", "Squame di drago x1"], "-"))
    zoolab.set_fiend_property("stats", "SCAGLIA EKYU", ("2000", "20", "12", "115", "Abilitosfera x2", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "SCAGLIA EMUZU", ("2400", "400", "0", "0", "-", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "SCAGLIA GHY", ("12000", "30", "400", "1000", "-", ["Pozione x1", "Pozione x1"], "-"))
    zoolab.set_fiend_property("stats", "SCAGLIA GHY", ("6000", "30", "0", "1000", "Passosfera Lv 1 x3", ["Pozione x1", "Pozione x1"], "-"))
    zoolab.set_fiend_property("stats", "SCAGLIA GUNAI", ("20000", "200", "1800", "10000", "Gamberosfera x1", ["Cortina stellare x1", "Eliomagilite x1"], "-"))
    zoolab.set_fiend_property("stats", "SCAGLIA GUNO", ("3000", "30", "48", "300", "Energosfera x2", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "SCOOR", ("1000", "60", "480", "420", "Energosfera x1", ["Onirolina x1", "Onirolina x2"], "-"))
    zoolab.set_fiend_property("stats", "SEYMOUR", ("6000", "100", "2000", "5000", "Mnerosfera x1", ["Turboetere x1", "Elisir x1"], "-"))
    zoolab.set_fiend_property("stats", "SEYMOUR BETA", ("70000", "512", "10000", "6000", "Passosfera Lv 4 x1", ["Elisir x1", "Elisir x1"], "-"))
    zoolab.set_fiend_property("stats", "SEYMOUR OMEGA", ("80000", "999", "24000", "12000", "Passosfera Lv 3 x1", ["Eliomagilite x1", "Examagilite x1"], "-"))
    zoolab.set_fiend_property("stats", "SFEROGESTORE", ("12000", "100", "3240", "4000", "Passosfera Lv 2 x1", ["Etere x1", "Turboetere x1"], "-"))
    zoolab.set_fiend_property("stats", "SHRED", ("1950", "30", "480", "368", "Velocisfera x1", ["Hypellina x1", "Hypellina x2"], "-"))
    zoolab.set_fiend_property("stats", "SHUMELKE", ("370", "70", "240", "138", "Velocisfera x1", ["Ago dorato x1", "Granata fossile x1"], "-"))
    zoolab.set_fiend_property("stats", "SHUMELKE KRYPT", ("550", "1", "240", "300", "Velocisfera x1", ["Ago dorato x1", "Granata fossile x1"], "-"))
    zoolab.set_fiend_property("stats", "SIGILLO ALBHED", ("1000", "1", "220", "300", "Pozione x1", ["Granpozione x1", "Granpozione x2"], "-"))
    zoolab.set_fiend_property("stats", "SIMURGH", ("200", "27", "48", "73", "Velocisfera x1", ["Lacrimogeno x1", "Lacrimogeno x2"], "-"))
    zoolab.set_fiend_property("stats", "SIN", ("2000", "100", "10", "100", "Magicosfera x1", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "SIN", ("36000", "999", "18000", "1000", "Emmepisfera x1", ["Fluido energetico x3", "Fluido energetico x4"], "-"))
    zoolab.set_fiend_property("stats", "SIN", ("140000", "999", "20000", "12000", "Passosfera Lv 3 x1", ["Etere x1", "Examagilite x1"], "-"))
    zoolab.set_fiend_property("stats", "SON", ("4080", "120", "830", "530", "Magicosfera x1", ["Mina Tacet x2", "Etere x1"], "-"))
    zoolab.set_fiend_property("stats", "SPLASHER", ("200", "2", "140", "100", "Energosfera x1", ["Granata x1", "Blindogranata x1"], "-"))
    zoolab.set_fiend_property("stats", "SPLASHER X2", ("400", "4", "300", "140", "Energosfera x1", ["Granata x1", "Blindogranata x1"], "-"))
    zoolab.set_fiend_property("stats", "SPLASHER X3", ("600", "6", "440", "200", "Energosfera x1", ["Granata x1", "Blindogranata x1"], "-"))
    zoolab.set_fiend_property("stats", "TEMPLARE", ("1400", "20", "420", "460", "Abilitosfera x1", ["Granpozione x2", "Sale purificatore x1"], "-"))
    zoolab.set_fiend_property("stats", "TEMPLARE", ("1400", "20", "420", "460", "Abilitosfera x1", ["Granpozione x2", "Sale purificatore x1"], "-"))
    zoolab.set_fiend_property("stats", "TEMPLARE REDIVIVO", ("3300", "1", "1200", "540", "Abilitosfera x1", ["Candela della vita x2", "Sale purificatore x1"], "-"))
    zoolab.set_fiend_property("stats", "TEMPLARE REDIVIVO", ("3300", "1", "1200", "540", "Abilitosfera x1", ["Candela della vita x2", "Sale purificatore x1"], "-"))
    zoolab.set_fiend_property("stats", "TENTACOLO DI GUNO", ("450", "10", "5", "30", "Abilitosfera x1", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "TESTA", ("4000", "200", "48", "200", "-", ["Pozione x1", "Pozione x1"], "-"))
    zoolab.set_fiend_property("stats", "THROS", ("2200", "10", "8", "100", "Energosfera x2", ["Granata x1", "Granata x3"], "-"))
    zoolab.set_fiend_property("stats", "THYTAN", ("3600", "1", "800", "600", "Energosfera x2", ["Cortina luminosa x1", "Cortina luminosa x1"], "-"))
    zoolab.set_fiend_property("stats", "TOMBERRY", ("13500", "1", "6500", "2000", "Energosfera x1", ["Granpozione x1", "Ombra d'Oltremondo x1"], "-"))
    zoolab.set_fiend_property("stats", "TRITO DI SCAGLIA", ("100", "0", "0", "0", "-", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "TRITO DI SCAGLIA", ("200", "0", "2", "22", "Energosfera x1", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "TRITO DI SCAGLIA", ("100", "0", "2", "24", "Magicosfera x1", ["-", "-"], ""))
    zoolab.set_fiend_property("stats", "TSUBASA", ("12000", "1000", "0", "0", "-", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "TSURUGI", ("20000", "1500", "0", "0", "-", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "ULTIMA WEAPON", ("70000", "1", "40000", "20000", "Passosfera Lv 3 x3", ["Porta sul domani x10", "Porta sul domani x20"], "-"))
    zoolab.set_fiend_property("stats", "ULTRA MIGHT (SPADA STELLA)", ("36000", "1", "7800", "1111", "Energosfera x1", ["Cortina lunare x1", "Cortina lunare x2"], "-"))
    zoolab.set_fiend_property("stats", "ULTRA MIGHT (SPADA NORMALE)", ("36000", "1", "7800", "1111", "Energosfera x1", ["Cortina lunare x1", "Cortina lunare x2"], "-"))
    zoolab.set_fiend_property("stats", "UNITA' 97", ("3700", "1", "3200", "1080", "Coda di fenice x2", ["Acquasanta x3", "Etere x2"], "-"))
    zoolab.set_fiend_property("stats", "UNITA' 99", ("2700", "1", "1870", "1300", "Coda di fenice x1", ["Panacea x1", "Etere x1"], "-"))
    zoolab.set_fiend_property("stats", "UNITA' BLINDATA 11", ("6200", "1", "3200", "1080", "Granpozione x2", ["Acquasanta x3", "Etere x2"], "Mawashigeri"))
    zoolab.set_fiend_property("stats", "UNITA' BLINDATA 63", ("6200", "1", "1870", "1300", "Granpozione x1", ["Panacea x1", "Etere x1"], "Mawashigeri"))
    zoolab.set_fiend_property("stats", "VARAHA", ("8700", "29", "1320", "720", "Abilitosfera x1", ["Granpozione x1", "Granpozione x2"], "Pirosbolle"))
    zoolab.set_fiend_property("stats", "VARNA", ("56000", "1", "19500", "1780", "Magicosfera x1", ["Vento d'Oltremondo x1", "Eliomagilite x1"], "-"))
    zoolab.set_fiend_property("stats", "VESPA", ("360", "30", "240", "142", "Velocisfera x1", ["Granpozione x1", "Zanna velenosa x1"], "-"))
    zoolab.set_fiend_property("stats", "VIHUR", ("225", "1", "14", "50", "Energosfera x1", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "VIVRE", ("225", "22", "24", "60", "Energosfera x1", ["Pozione x1", "Clessidra d'argento x1"], "-"))
    zoolab.set_fiend_property("stats", "WENDIGO", ("18000", "32", "2000", "3000", "Energosfera x1", ["Granpozione x1", "Extrapozione x1"], "-"))
    zoolab.set_fiend_property("stats", "YENKE RONSO", ("Variabile", "200", "4500", "1500", "Gamberosfera x1", ["Passosfera Lv 3 x1", "Passosfera Lv 3 x2"], "4 Nemitec diverse"))
    zoolab.set_fiend_property("stats", "YOJIMBO", ("33000", "2000", "0", "0", "-", ["-", "-"], "-"))
    zoolab.set_fiend_property("stats", "YOWIE", ("900", "95", "810", "480", "Velocisfera x1", ["Ago dorato x1", "Granata fossile x1"], "-"))
    zoolab.set_fiend_property("stats", "YUNALESCA I", ("24000", "500", "0", "0", "Passosfera Lv 3 x1", ["Nettare energetico x1", "Vento d'Oltremondo x1"], "-"))
    zoolab.set_fiend_property("stats", "YUNALESCA II", ("48000", "500", "0", "0", "Passosfera Lv 3 x1", ["Nettare energetico x1", "Vento d'Oltremondo x1"], "-"))
    zoolab.set_fiend_property("stats", "YUNALESCA III", ("60000", "500", "14000", "9000", "Passosfera Lv 3 x1", ["Nettare energetico x1", "Vento d'Oltremondo x1"], "-"))
    zoolab.set_fiend_property("stats", "ZAURAS", ("7850", "1", "5000", "950", "Velocisfera x1", ["Granata fossile x2", "Granata fossile x3"], ""))
    zoolab.set_fiend_property("stats", "ZUU (ingresso bikanel)", ("12000", "50", "1200", "1200", "Energosfera x1, Albhedina x1", ["Lacrimogeno x3", "Lacrimogeno x4"], "-"))
    zoolab.set_fiend_property("stats", "ZUU", ("18000", "50", "1200", "1200", "Energosfera x1, Albhedina x1", ["Lacrimogeno x3", "Lacrimogeno x4"], "-"))

    zoolab.add_area_conquest('Trusthevis', 'Besaid', '99 Filtri energetici', '320.000', '115', '10.000', ('Lacrimogeno x 3', 'Filtro energetico x 2'), 'Amuleto x 2', 'RES 0% a Spot, Scan, Antima, Moviola e Spazzata, e RES 90% a Zombie ed Anti' )
    zoolab.add_area_conquest('Molboro Beta', 'Kilika', '99 Zanne velenose', '640.000', '200', '12.000', ('Panacea x 4', 'Fluido magico x 2'), 'Filtro magico x 2', 'Fuoco x1.5, assorbe acqua' )
    zoolab.add_area_conquest('Kolossos', 'Via Mihen', '99 Fluidi vitali', '440.000', '20', '15.000', ('Fluido energetico x 4', 'Fluido vitale x 2'), 'Fluido rigenerante x 20', '' )
    zoolab.add_area_conquest('Iaguaro regina', 'Via Micorocciosa', '99 Candele della vita', '380.000', '80', '10.000', ('Vento d\'Oltremondo x 2', 'Sacromagilite x 1'), 'Eliomagilite x 3', '' )
    zoolab.add_area_conquest('Yormungand', 'Via Djose', '99 Granate fossili', '520.000', '63', '10.000', ('Granata fossile x 4', 'Triostella x 1'), 'Examagilite x 2', 'RES 0% a Zombie, e RES 90% agli Anti' )
    zoolab.add_area_conquest('Kyactus', 'Piana dei Lampi', '99 Piume di Chocobo', '100.000', '0', '10.000', ('Piuma di chocobo x 2', 'Portafoglio gonfio x 1'), 'Sacromagilite x 3', '' )
    zoolab.add_area_conquest('Espada', 'Macalania', '99 Eliomagiliti', '280.000', '120', '15.000', ('Ombra d\'Oltremondo x 4', 'Vento d\'Oltremondo x 1'), 'Carta d\'identita x 1', 'RES 0% agli Anti e RES 50% a Zombie' )
    zoolab.add_area_conquest('Abyss Worm', 'Bikanel', '99 Neromagiliti', '480.000', '200', '12.000', ('Neromagilite x 4', 'Nettare energetico x 1'), 'Filtro energetico x 1', '' )
    zoolab.add_area_conquest('Chimera X', 'Piana della Bonaccia', 'Vento d\'Oltremondo x 60', '120.000', '30', '10.000', ('Filtro magico x 2', 'Fluido energetico x 2'), 'Gamberosfera x 1', 'RES 50% agli Anti' )
    zoolab.add_area_conquest('Don Tomberry', 'Grotta del Crepaccio', '40 Clessidre d\'argento', '480.000', '120', '10.000', ('Candela della vita x 2', 'Portafoglio gonfio x 1'), 'Vento d\'Oltremondo x 3', '' )
    zoolab.add_area_conquest('Catoblepas', 'Monte Gagazet', 'Corona di Boccioli', '550.000', '160', '10.000', ('Fluido rigenerante x 3', 'Filtro energetico x 1'), 'Triostella x 1', 'RES 50% agli Anti' )
    zoolab.add_area_conquest('Abadon', 'Dentro Sin', '99 Cortie lunari', '380.000', '780', '10.000', ('Sale purificatore x 3', 'Eliomagilite x 1'), 'Nettare magico x 1', '' )
    zoolab.add_area_conquest('Vorban', 'Rovine di Omega', 'Portafoglio gonfio x 60', '630.000', '120', '10.000', ('Fluido rigenerante x 2', 'Nettare energetico x 1'), 'Empatosfera x 1', '' )

    zoolab.set_species_conquest('Fenril', 3, '99 Code di Chocobo', '850.000', '300', '99.999', ('Coda di Chocobo x 2', 'Piuma di Chocobo x 1'), 'Rapidosfera x 1', '' )
    zoolab.set_species_conquest('Ornitorestes', 3, '99 Fluidi energetici', '800.000', '300', '99.999', ('Carta d\'Identita x 1', 'Piuma di Chocobo x 1'), 'Anima del baro x 2', '' )
    zoolab.set_species_conquest('Pterix', 4, '99 Megafenici', '100.000', '0', '99.999', ('Lacrimogeno x 4', 'Candela della vita x 1'), 'Destrosfera x 1', 'RES 90% agli Anti' )
    zoolab.set_species_conquest('Honet', 4, '60 Filtri magici', '620.000', '180', '50.000', ('Zanna velenosa x 4', 'Sale purificatore x 2'), 'Mirasfera x 1', 'RES 0% a Mutismo, RES 95% agli Anti' )
    zoolab.set_species_conquest('Vizalsha', 4, '99 Fluidi magici', '95.000', '840', '10.000', ('Elettromagilite x 4', 'Filtro magico x 1'), 'Emmepisfera x 1', 'RES 80% ad Antikelesis e Antimajix, RES 99% ad Antiscutum' )
    zoolab.set_species_conquest('Unioculum', 4, '60 Nettari energetici', '150.000', '270', '15.000', ('Cortina lunare x 3', 'Sacromagilite x 1'), 'Difesfera mag x 1', 'RES 0% a Antivis e Antikelesis' )
    zoolab.set_species_conquest('Budino Jumbo', 3, '60 Duostelle', '1.300.000', '999', '99.999', ('Cortina lunare x 4', 'Nettare magico x 1'), 'Potesfera mag x 1', '' )
    zoolab.set_species_conquest('Elemento Nega', 3, '99 Cortine Stellari', '1.300.000', '20', '15.000', ('Cortina lunare x 4', 'Duostella x 1'), 'Duostella x 2', '' )
    zoolab.set_species_conquest('Tanket', 3, '99 Clessidre d\'oro', '900.000', '0', '10.000', ('Cortina luminosa x 4', 'Cortina lunare x 4'), 'Difesfera fis x 1', '' )
    zoolab.set_species_conquest('Fefnil', 4, '99 Sali Purificatori', '1.100.000', '30', '13.000', ('Clessidra d\'oro x 2', 'Fluido energetico x 2'), 'Cortina luminosa x 20', '' )
    zoolab.set_species_conquest('Sonnellino', 5, '99 Fluidi rigeneranti', '98.000', '820', '10.000', ('Zanna velenosa x 4', 'Vento d\'Oltremondo x 1'), 'Telesfera x 1', 'RES 0% ad Antivis' )
    zoolab.set_species_conquest('Re Piros', 5, '60 Turboetere', '480.000', '780', '10.000', ('Magmagilite x 4', 'Eliomagilite x 1'), 'Porta sul domani x 1', '' )
    zoolab.set_species_conquest('Juggernaut', 5, '99 Cortine luminose', '1.200.000', '20', '15.000', ('Cortina lunare x 4', 'Eliomagilite x 1'), 'Potesfera fis x 1', 'RES 95% agli Anti' )
    zoolab.set_species_conquest('Clod d\'acciaio', 10, '90 Nettari Magici', '2.000.000', '0', '99.999', ('Cortina luminosa x 4', 'Nettare energetico x 1'), 'Accapisfera x 1', 'RES 95% a Antikelesis, Antiscutum e Antimajix' )

    zoolab.add_original('Mangiaterra', 'Generare 2 creature della categoria campioni di zona','60 Triostelle', '1.300.000', '30', '99.999', ('', 'Passosfera Lv 1 x 1'), 'Fatosfera x 1', '')
    zoolab.add_original('Titanosfera', 'Generare 2 creature della categoria campioni di specie', '60 Examagiliti', '1.500.000', '999', '99.999', ('', 'Gamberosfera x 1'), 'Fortunosfera x 1', '')
    zoolab.add_original('Catastrophe', 'Generare 6 creature della categoria campioni di zona', '99 Porte sul domani', '2.200.000', '380', '99.999', ('', 'Passosfera Lv 2 x 1'), 'Portafoglio gonfio x 1', '')
    zoolab.add_original('Vlakorados', 'Generare 6 creature della categoria campioni di specie', '99 Anime del baro', '3.000.000', '85', '99.999', ('', 'Telesfera x 1'), 'Controchiave x 1', '')
    zoolab.add_original('Gasteropodos', 'Catturare un esemplare di ogni mostro', '99 Equazioni cubiche', '4.000.000', '999', '12.000', ('', 'Empatosfera x 1'), 'Pendulum x 1', 'RES 0% a Mutismo')
    zoolab.add_original('Ultima X', 'Catturare 5 esemplari di ogni mostro', '99 Materioscure', '5.000.000', '140', '99.999', ('', 'Passosfera Lv 3 x 1'), 'Equazione cubica x 1', '')
    zoolab.add_original('Shinryu', 'Catturare 2 esemplari di Splasher, Aquelous ed Echenesis nel Monte Gagazet', '30 Megaelisir', '2.000.000', '72', '99.999', ('', 'Triostella x 1'), 'Ali per l\'ignoto x 1', '')
    zoolab.add_original('Il Supremo', 'Catturare 10 esemplari di ogni mostro e sconfiggere tutti i campioni di zona, tutti i campioni di specie e tutti i prototipi zoolab almeno una volta', '10 Mastersfere', '10.000.000', '9.999', '99.999', ('Passosfera Lv 4 x 1', 'Onnisfera x 1'), 'Onnisfera x 1', '')

    with open(path, 'w') as db:
        db.write(json.dumps(zoolab.dict()))

if __name__ == '__main__':
    create_zoolab('../database/database.json')

