const fs = require('fs');
//const scanf = require('scanf');

function cap(string) {
    if (!string) return ''
    let newString
    if (/\s/g.test(string)) {
        const nonWords = string.match(/\s/g)
        string = string.split(/\s/g).map(x => x[0].toUpperCase() + x.substr(1))
        newString = string[0]
        for (let i = 0; i < nonWords.length; i++) newString += nonWords[i] + string[i + 1]
    } else
        newString = string[0].toUpperCase() + string.slice(1)
    return newString
}

function splitCamel(word) {
    if (!word.match(/[a-z][A-Z]/g)) return word
    const humps = word.match(/[a-z][A-Z]/g).map(x => x.split('').join(' '))
    word = word.split(/[a-z][A-Z]/g)
    let res = ''
    for (let i = 0; i < humps.length; i++)
        res += word[i] + humps[i]
    res += word[word.length - 1]
    return res
}



function addProperty(fiend, property, value, bind) {
    for (let zone in bind.bestiario) {
        zone = bind.bestiario[zone]
        for (let bestiarioFiend in zone)
            if (bestiarioFiend === fiend)
                return zone[bestiarioFiend][property] = value
    }
    bind.addFiend("Others", fiend, false, false)
    bind.bestiario.Others[fiend][property] = value
    bind.bestiario.Others[fiend].isNeeded = false
}

const zoolab = {
    bestiario: {},
    addFiend(zone, name, createsChampion, capturable = true) {
        name = cap(name.toLowerCase())
        if (!(zone in this.bestiario))
            this.bestiario[zone] = {}
        this.bestiario[zone][name] = {
            name,
            createsChampion,
            isNeeded: true,
            wasCaptured: 0,
            capturable
        }
    },

    addChampion(kind, name, reward, properties = { zoneRequired: '', kindRequired: false, fiendsForKind: 0, stats: { hp: '0', uc: '0', mp: '0', ruba: { normale: '', raro: '' }, oggetto: '' } }) {
        if (!(kind in this))
            this[kind] = {}
        this[kind][name] = {
            name,
            exist: false,
            wasDefeated: false,
            reward
        }
        if (properties.zoneRequired)
            this[kind][name].zoneRequired = cap(properties.zoneRequired)
        if (properties.kindRequired) {
            let kR = this[kind][name].kindRequired = {}
            kR.fiends = this.sameKindFiends(name)
            kR.quantity = properties.fiendsForKind
        }
        if (properties.stats) {
            let s = this[kind][name].stats = {}
            let ps = properties.stats
            s.hp = ps.hp
            s.mp = ps.mp
            s.ultracidio = ps.uc
            s.ruba = ps.ruba
            s.oggetto = ps.oggetto
            if (ps.debolezza) s.debolezza = ps.debolezza
        }
    },

    sameKindFiends(champion) {
        let fiends = []
        for (let zone in this.bestiario) {
            let thisZone = this.bestiario[zone]
            for (let fiend in thisZone)
                if (thisZone[fiend].createsChampion === champion)
                    fiends.push(fiend)
        }
        return fiends
    },

    bribe(array) {
        let [fiend, guil, reward] = array
        fiend = cap(splitCamel(fiend).toLowerCase())
        guil = Number(guil.replace(/\./g, ''))
        reward = `${reward.slice(reward.indexOf(reward.match(/^[\d\s]+(\w)/)[1]))} x ${reward.match(/^\d+/)[0]}`
        addProperty(fiend, 'bribe', { guil, reward }, this)
    },

    stats(array) {
        let [fiend, hp, mp, ap, guil, reward, ruba, nemitec] = array.map(x => Number(x) ? Number(x) : x)
        fiend = cap(fiend.toLowerCase())
        const steal = ruba[0] !== '-' && ruba[1] !== '-' ? {
            normal: ruba[0],
            rare: ruba[1]
        } : null
        nemitec = nemitec === '-' ? false : nemitec
        const stat = {
            hp,
            mp,
            ap,
            guil,
            reward,
            steal,
            nemitec
        }
        addProperty(fiend, 'stats', stat, this)
    },

    weaponReward(name, ...weapons) {
        name = cap(name.toLowerCase())
        addProperty(name, 'weaponReward', weapons, this)
    },
}

const newFiend = (zone, name, createsChampion = false, capturable = true) => zoolab.addFiend(cap(zone), cap(name), cap(createsChampion))
const newChampion = (kind, name, reward, properties) => zoolab.addChampion(cap(kind), cap(name), reward, properties)
const newBribe = array => zoolab.bribe(array)
const newStats = array => zoolab.stats(array)
const newWeaponReward = (name, ...weapons) => zoolab.weaponReward(name, ...weapons)

for (let zone in zoolab.bestiario)
    zoolab.bestiario[zone].isNeeded = true

newFiend('Besaid', 'dingo', 'Fenril')
newFiend('Besaid', 'condor', 'Pterix')
newFiend('Besaid', 'budino d\'acqua', 'Budino Jumbo')

newFiend('kilika', 'Deinonychus', "Ornitorestes")
newFiend('kilika', "Ape Killer", "Honet")
newFiend('kilika', "Elemento Giallo", "Elemento Nega")
newFiend('kilika', "Balsamiko")

newFiend('Via Mihen', "Mihen Phang", "Fenril")
newFiend('Via Mihen', "Ipiria", "Ornitorestes")
newFiend('Via Mihen', "Occhio fluttuante", "Unioculum")
newFiend('Via Mihen', "Elemento Bianco", "Elemento Nega")
newFiend('Via Mihen', "Rarth", "Tanket")
newFiend('Via Mihen', "Vivre", "Fefnil")
newFiend('Via Mihen', "Piros", "Re Piros")
newFiend('Via Mihen', "Bikorno", "Juggernaut")

newFiend('Via Micorocciosa', "Raptor", "Ornitorestes")
newFiend('Via Micorocciosa', "Gandharva", "Vizalsha")
newFiend('Via Micorocciosa', "Budino di tuono", "Budino Jumbo")
newFiend('Via Micorocciosa', "Elemento rosso", "Elemento Nega")
newFiend('Via Micorocciosa', "Ramashut", "Fefnil")
newFiend('Via Micorocciosa', "Fungongo", "Sonnellino")
newFiend('Via Micorocciosa', "Garuda")

newFiend('Via Djose', "Garm", "Fenril")
newFiend('Via Djose', "Simurgh", "Pterix")
newFiend('Via Djose', "Lesmathor", "Honet")
newFiend('Via Djose', "Budino di neve", "Budino Jumbo")
newFiend('Via Djose', "Bunyips", "Tanket")
newFiend('Via Djose', "Basilisk")
newFiend('Via Djose', "Ochu")

newFiend('Piana dei lampi', "Meryujin", "Ornitorestes")
newFiend('Piana dei lampi', "Aroj", "Vizalsha")
newFiend('Piana dei lampi', "Buel", "Unioculum")
newFiend('Piana dei lampi', "Elemento dorato", "Elemento Nega")
newFiend('Piana dei lampi', "Kusarik", "Fefnil")
newFiend('Piana dei lampi', "Larva")
newFiend('Piana dei lampi', "Thytan", "Clod D'acciaio")
newFiend('Piana dei lampi', "Kyactus")

newFiend('Macalania', "Lupo delle nevi", "Fenril")
newFiend('Macalania', "Shumelke")
newFiend('Macalania', "Vespa", "Honet")
newFiend('Macalania', "Occhio diabolico", "Unioculum")
newFiend('Macalania', "Budino di Ghiaccio", "Budino Jumbo")
newFiend('Macalania', "Elemento Blu", "Elemento Nega")
newFiend('Macalania', "Mulfus", "Tanket")
newFiend('Macalania', "Mafut", "Tanket")
newFiend('Macalania', "Kushipos")
newFiend('Macalania', "Chimera")

newFiend('Bikanel', "Lupo del deserto", "Fenril")
newFiend('Bikanel', "Alcione", "Pterix")
newFiend('Bikanel', "MushuHushu", "Fefnil")
newFiend('Bikanel', "Zuu")
newFiend('Bikanel', "Anellidus")
newFiend('Bikanel', "Kyactus?")

newFiend('Piana della Bonaccia', "Scoor", "Fenril")
newFiend('Piana della Bonaccia', "Nebiros", "Honet")
newFiend('Piana della Bonaccia', "Budino di fiamme", "Budino Jumbo")
newFiend('Piana della Bonaccia', "Shred", "Tanket")
newFiend('Piana della Bonaccia', "Anacondar")
newFiend('Piana della Bonaccia', "Hoga")
newFiend('Piana della Bonaccia', "Iaguaro")
newFiend('Piana della Bonaccia', "Chimera Brain")
newFiend('Piana della Bonaccia', "Molboro")

newFiend('Grotta del Crepaccio', "Yowie", "Ornitorestes")
newFiend('Grotta del Crepaccio', "Galkimasela", "Vizalsha")
newFiend('Grotta del Crepaccio', "Elemento scuro", "Elemento Nega")
newFiend('Grotta del Crepaccio', "Heg", "Fefnil")
newFiend('Grotta del Crepaccio', "Son", "Sonnellino")
newFiend('Grotta del Crepaccio', "Varaha", "Juggernaut")
newFiend('Grotta del Crepaccio', "Epej")
newFiend('Grotta del Crepaccio', "Fantasma")
newFiend('Grotta del Crepaccio', "Tomberry")

newFiend('Monte Gagazet', "Mal Bernardo", "Fenril")
newFiend('Monte Gagazet', "Alyman", "Unioculum")
newFiend('Monte Gagazet', "Budino oscuro", "Budino Jumbo")
newFiend('Monte Gagazet', "Granad", "Re Piros")
newFiend('Monte Gagazet', "Grat")
newFiend('Monte Gagazet', "Grendel", "Juggernaut")
newFiend('Monte Gagazet', "Ashoor")
newFiend('Monte Gagazet', "Mandragora")
newFiend('Monte Gagazet', "Behemoth")
newFiend('Monte Gagazet', "Splasher")
newFiend('Monte Gagazet', "Aquelous")
newFiend('Monte Gagazet', "Echeneis")

newFiend('Dentro Sin', "Exoray", "Sonnellino")
newFiend('Dentro Sin', "Alyadin")
newFiend('Dentro Sin', "Ultra Might L", "Clod D'acciaio")
newFiend('Dentro Sin', "Ultra Might R", "Clod D'acciaio")
newFiend('Dentro Sin', "Demomonolix")
newFiend('Dentro Sin', "Molboro il Grande")
newFiend('Dentro Sin', "Barbatos")
newFiend('Dentro Sin', "Adamanthart")
newFiend('Dentro Sin', "King Behemoth")

newFiend('Rovine di Omega', "Zauras", "Ornitorestes")
newFiend('Rovine di Omega', "Byurobolos", "Re Piros")
newFiend('Rovine di Omega', "Desflot", "Unioculum")
newFiend('Rovine di Omega', "Elemento nero", "Elemento Nega")
newFiend('Rovine di Omega', "Haruma", "Tanket")
newFiend('Rovine di Omega', "Esprit")
newFiend('Rovine di Omega', "Mechy")
newFiend('Rovine di Omega', "Master Iaguaro")
newFiend('Rovine di Omega', "Mastro Tomberry")
newFiend('Rovine di Omega', "Varna")

newBribe(["Adamanthart", "1.360.000", "1Qualitosfera"])
newBribe(["Alcione", "10.750", "2 Megafenice"])
newBribe(["Alyadin", "555.550", "60 Vento d'Oltremondo"])
newBribe(["Alyman", "70.000", "6 Vento d'Oltremondo"])
newBribe(["Anacondar", "145.000", "16 Acqua Curativa"])
newBribe(["Anellidus", "1.125.000", "15 Equazione Cubica"])
newBribe(["Ape Killer", "2.750", "1 Zanna Velenosa"])
newBribe(["Aquelous", "127.500", "16 Fluido Rigenerante"])
newBribe(["Aroj", "5.000", "4 Razzo Fulminante"])
newBribe(["Ashoor", "425.000", "80 Fluido Energetico"])
newBribe(["Autoarmatura", "217.500", "99 Albhedina"])
newBribe(["Autoartigliere", "70.000", "40 Albhedina"])
newBribe(["Autocacciatore", "137.500", "60 Albhedina"])
newBribe(["Autocommander", "92.500", "2 Porta sul Domani"])
newBribe(["Autoguardiano", "32.000", "50 Granata"])
newBribe(["Autoscout", "68.750", "1 Porta sul Domani"])
newBribe(["Balsamiko", "19.500", "8 Panacea"])
newBribe(["BalsamikoGrasso", "318.750", "99 Panacea"])
newBribe(["Barbatos", "2.375.000", "20 Telesfera"])
newBribe(["Basilisk", "50.625", "24 Granata fossile"])
newBribe(["Behemoth", "575.000", "30 Passosfera lv 2"])
newBribe(["Bikorno", "46.875", "60 Granpozione"])
newBribe(["Bikorno (CovoAlbhed)", "94.875", "25 Megapozione"])
newBribe(["Budino d'Acqua", "7.875", "15 Idromagilite"])
newBribe(["Budino d'Acqua (Canale purificatorio Yuna)", "50.625", "2 Idromagilite"])
newBribe(["Budino diFiamme", "37.500", "10 Magmagilite"])
newBribe(["Budino diGhiaccio", "33.750", "9 Criomagilite"])
newBribe(["Budino diNeve", "15.000", "10 Vento Antartico"])
newBribe(["Budino diTuono", "11.250", "8 Razzo Fulminante"])
newBribe(["Budino Oscuro", "320.000", "2MBiancosfera"])
newBribe(["Buel", "5.750", "2 Stricnina"])
newBribe(["Bunyips", "10.000", "16 Hypellina"])
newBribe(["Byurobolos", "500.000", "36Eliomagilite"])
newBribe(["Chimera", "131.250", "10 Nettare Magico"])
newBribe(["Chimera (CovoAlbhed)", "225.000", "15Controchiave"])
newBribe(["Chimera Brain", "245.000", "2 Passosfera lv 4"])
newBribe(["Condor", "2.375", "3 Lacrimogeno"])
newBribe(["Dedalarva", "55.550", "14Idromagilite"])
newBribe(["Defender", "300.000", "20 Nettare Energetico"])
newBribe(["Defender Zero", "1.057.500", "5 Portafoglio Gonfio"])
newBribe(["Deinonychus", "3.500", "2 Granata Fossile"])
newBribe(["Demomonolix", "1.125.000", "40 Passosfera lv 3"])
newBribe(["Desflot", "167.500", "10 Anima delBaro"])
newBribe(["Dingo", "3.125", "4 Melatonina"])
newBribe(["Echeneis", "250.000", "1Parametrosfera"])
newBribe(["Elemento Bianco", "9.750", "7 Vento Antartico"])
newBribe(["Elemento Blu", "375.000", "19Idromagilite"])
newBribe(["Elemento dorato", "30.000", "20 Razzo Fulminante"])
newBribe(["Elemento Giallo", "7.500", "6 Razzo Fulminante"])
newBribe(["Elemento Nero", "190.000", "2 MNerosfera"])
newBribe(["Elemento Rosso", "11.250", "8 Anima di Piros"])
newBribe(["Elemento Scuro", "45.000", "3Gamberosfera"])
newBribe(["Epej", "217.500", "25 Vento d'Oltremondo"])
newBribe(["Esprit", "250.000", "10 Duostella"])
newBribe(["Exoray", "185.000", "30 Turboetere"])
newBribe(["Fantasma", "249.975", "38 Megafenice"])
newBribe(["Fungongo", "13.500", "2 Turboetere"])
newBribe(["Galkimasela", "22.000", "4 Passosfera lv 1"])
newBribe(["Gandharva", "3.700", "3 Razzo Fulminante"])
newBribe(["Garm", "6.000", "7 Melatonina"])
newBribe(["Garuda", "100.000", "99Lacrimogeno"])
newBribe(["Granad", "187.500", "12Eliomagilite"])
newBribe(["Grat", "100.000", "40 Panacea"])
newBribe(["Grendel", "237.500", "60Megapozione"])
newBribe(["Guardia Guado(Tempio di Macalania)", "50.000", "10 Etere"])
newBribe(["Guardia Guado(Covo Albhed)", "65.000", "30Extrapozione"])
newBribe(["Haruma", "325.000", "20Examagilite"])
newBribe(["Heg", "50.000", "12 Clessidra d'Oro"])
newBribe(["Hoga", "235.000", "50 Fluido Energetico"])
newBribe(["Iaguaro", "150.000", "2 Empatosfera"])
newBribe(["Ipiria", "4.500", "3 Granata Fossile"])
newBribe(["King Behemoth", "1.687.500", "14 Triostella"])
newBribe(["Kusarik", "11.125", "20 Clessidra d'Argento"])
newBribe(["Kushipos", "67.500", "1 Megaelisir"])
newBribe(["Larva", "37.450", "10 Spina Iperica"])
newBribe(["Lesmathor", "5.000", "2 Zanna Velenosa"])
newBribe(["Lumbrikus", "2.000.000", "2Materioscura"])
newBribe(["Lupo del Deserto", "11.250", "12 Melatonina"])
newBribe(["Lupo delle Nevi", "10.000", "11 Melatonina"])
newBribe(["Mafut", "17.750", "28 Hypellina"])
newBribe(["Mal Bernardo", "45.000", "20 Onirolina"])
newBribe(["Mandragora", "775.000", "24Gamberosfera"])
newBribe(["MasterIaguaro", "325.000", "1 Onnisfera"])
newBribe(["MastroTomberry", "1.200.000", "3 Pendulum"])
newBribe(["Mechy", "450.000", "60 Piuma di Chocobo"])
newBribe(["Meryujin", "6.625", "4 Granata fossile"])
newBribe(["Mihen Phang", "4.000", "5 Melatonina"])
newBribe(["Molboro", "675.000", "4 Ali per l'Ignoto"])
newBribe(["Molboro ilGrande", "1.600.000", "8 Ali per l'Ignoto"])
newBribe(["Mulfus", "14.500", "24 Hypellina"])
newBribe(["Mushuhushu", "17.000", "5 Clessidra d'Oro"])
newBribe(["Nebiros", "17.500", "6 Zanna Velenosa"])
newBribe(["OcchioDiabolico", "7.750", "3 Stricnina"])
newBribe(["OcchioDiabolico (Covo Albhed)", "10.750", "4 Stricnina"])
newBribe(["OcchioFluttuante", "3.500", "1 Stricnina"])
newBribe(["OcchioMalvagio", "9.500", "12 Mina Tacet"])
newBribe(["Ochu", "180.000", "70 Panacea"])
newBribe(["Ochu Smarrito", "116.225", "80 Panacea"])
newBribe(["Octopus", "112.500", "20 Fluido Rigenerante"])
newBribe(["Paludomafut", "21.250", "32 Hypellina"])
newBribe(["Phlegyas", "42.000", "6 Fluido Rigenerante"])
newBribe(["Piranha", "1.250", "1Idromagilite"])
newBribe(["Piranha x2", "2.500", "1Idromagilite"])
newBribe(["Piranha x3", "3.750", "2 Idromagilite"])
newBribe(["Piros", "21.250", "16 Anima di Piros"])
newBribe(["Piros (CovoAlbhed)", "55.000", "14Magmagilite"])
newBribe(["Ramashut", "6.875", "10 Clessidra d'Argento"])
newBribe(["Raptor", "5.000", "3 Granata Fossile"])
newBribe(["Rarth", "6.000", "10 Hypellina"])
newBribe(["Remora", "75.000", "20Idromagilite"])
newBribe(["Sahagin(Canale Purificatorio Yuna)", "34.500", "8Idromagilite"])
newBribe(["Sahagin(Canale Purificatorio Tidus)", "9.500", "3Idromagilite"])
newBribe(["Scoor", "25.000", "12 Onirolina"])
newBribe(["Shred", "48.750", "50 Hypellina"])
newBribe(["Shumelke", "9.250", "5 Granata Fossile"])
newBribe(["Shumelke Krypt", "13.750", "6 Granata Fossile"])
newBribe(["Simurgh", "5.000", "5 Lacrimogeno"])
newBribe(["Son", "102.000", "16 Turboetere"])
newBribe(["Splasher", "5.000", "4 Squame di Drago"])
newBribe(["Splasher x2", "10.000", "8 Squame di Drago"])
newBribe(["Splasher x3", "15.000", "12 Squame di Drago"])
newBribe(["Thytan", "90.000", "1 Filtro Energetico"])
newBribe(["Tomberry", "337.500", "2 Amuleto"])
newBribe(["Ultima Weapon", "2.499.975", "99 Pendulum"])
newBribe(["Ultra Might(Spada stella)", "900.000", "10 Filtro Energetico"])
newBribe(["Ultra Might(Spada normale)", "900.000", "10 Filtro Magico"])
newBribe(["Unità 97", "92.500", "16 Etere"])
newBribe(["Unità 99", "67.500", "10 Etere"])
newBribe(["UnitàBlindata 11", "155.000", "12 Elisir"])
newBribe(["UnitàBlindata 63", "105.000", "8 Elisir"])
newBribe(["Varaha", "217.500", "60Extrapozione"])
newBribe(["Varna", "1.400.000", "2 Megaelisir"])
newBribe(["Vespa", "9.000", "3 Zanna Velenosa"])
newBribe(["Vihur", "6.375", "10 Clessidra d'Argento"])
newBribe(["Yowie", "22.500", "12 Granata Fossile"])
newBribe(["Zauras", "196.250", "10 Carta d'Identità"])
newBribe(["Zuu", "450.000", "2 Tecnisfera"])

newWeaponReward("ADAMANTHART", "Perforazione, Consumo ½ MP", "Riserva Shell, Riserva Protect, HP +20%")
newWeaponReward("ALCIONE", "Spot, Perforazione, Induttore V", "DIF Blind, DIF Mag +5%")
newWeaponReward("ALYADIN", "Perforazione, ATT Mag +5%, ATT Mag +10%,Induttore M", "MP+10%, Incontri 0")
newWeaponReward("ALYMAN", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Att Fis +5%, ATT Mag +5%", "DIF Caos")
newWeaponReward("ANACONDAR", "Perforazione, ATT Pietra, ATT Fis +5%, ATT Mag+5%", "DIF Pietra")
newWeaponReward("ANELLIDUS", "Perforazione, ATT Lentezza, ATT Fis +5%, ATTMag +5%", "HP +10%, Autopozione")
newWeaponReward("ANIMA", "Perforazione, ATT Blind, ATT Mutismo, ATTSonno", "DIF Blind, DIF Mutismo, DIF Sonno")
newWeaponReward("APE KILLER", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Veleno, MP +5%")
newWeaponReward("AQUELOUS", "Perforazione, ATT Fis +5%, ATT Mag +10%", "MP +10%, Autopanacea")
newWeaponReward("AROJ", "Perforazione, Tuonattacco, Induttore M", "Tuono -50%, Immunotuono, DIF Mag +5%")
newWeaponReward("ASHOOR", "Perforazione, ATT Fis +5%, ATT Mag +5%,Contrattacco", "Riserva Haste, HP +10%")
newWeaponReward("AUTOARMATURA", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva: Parafire, Parathund, Paraidro,Parabliz, Shell, Protect, Reflex")
newWeaponReward("AUTOARTIGLIERE", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva: Parafire, Parathund, Paraidro,Parabliz, Shell, Protect, Reflex")
newWeaponReward("AUTOCACCIATORE", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva: Parafire, Parathund, Paraidro,Parabliz, Shell, Protect, Reflex")
newWeaponReward("AUTOCOMMANDER", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva: Parafire, Parathund, Paraidro,Parabliz")
newWeaponReward("AUTOGUARDIANO", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva: Parafire, Parathund, Paraidro,Parabliz")
newWeaponReward("AUTOSCOUT", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva: Parafire, Parathund, Paraidro,Parabliz")
newWeaponReward("BALSAMIKO", "Perforazione, ATT Veleno, ATT Fis +3%, ATT Mag+3%", "DIF Veleno, HP +5%")
newWeaponReward("BALSAMIKO GRASSO", "Perforazione, ATT Veleno, ATT Fis +3%, ATT Mag+3%", "DIF Veleno, HP +5%, HP +10%")
newWeaponReward("BARBATOS", "Perforazione", "MP +20%")
newWeaponReward("BASILISK", "Perforazione, ATT Pietra, ATT Fis +3%, ATT Mag+3%", "DIF Pietra, MP +5%")
newWeaponReward("BEHEMOTH", "Perforazione, ATT Zombie, ATT Fis +5%, ATT Mag+5%, Riserva Turbo", "Riserva Shell, Riserva Protect, Riserva Reflex")
newWeaponReward("BIKORNO", "Perforazione, Fuocattacco, ATT Mutismo,Induttore A", "HP +5%")
newWeaponReward("BIKORNO", "Perforazione, Fuocattacco, ATT Mutismo,Induttore A", "HP +5%, HP +10%")
newWeaponReward("BIRAN RONSO", "Perforazione", "MP +20%")
newWeaponReward("BRACCIO", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%")
newWeaponReward("BRACCIO DX DI SIN", "Perforazione, ATT Pietra +", "DIF Pietra +")
newWeaponReward("BRACCIO SX DI SIN", "Perforazione, ATT Veleno +", "DIF Veleno +")
newWeaponReward("BUDINO D'ACQUA", "Perforazione, Acquattacco, Induttore M", "Acqua -50%, Immunoacqua")
newWeaponReward("BUDINO D'ACQUA", "Perforazione, Acquattacco, Induttore M", "Acqua -50%")
newWeaponReward("BUDINO DI FIAMME", "Perforazione, Fuocattacco, Induttore M", "Fuoco +50%, Immunofuoco")
newWeaponReward("BUDINO DI GHIACCIO", "Perforazione, Gelattacco, Induttore M", "Gelo +50%, Immunofuoco")
newWeaponReward("BUDINO DI NEVE", "Perforazione, Gelattacco, Induttore M", "Gelo +50%, Immunofuoco")
newWeaponReward("BUDINO DI TUONO", "Perforazione, Tuonattacco, Induttore M", "Gelo +50%, Immunotuono")
newWeaponReward("BUDINO OSCURO", "Perforazione, ATT Mag +5%, ATT Mag +10%,Induttore M", "MP +10%, MP +20%")
newWeaponReward("BUEL", "Perforaz., Fuocattac., Tuonattac., Acquattac.,Gelattac., ATT Fis +3%, ATT Mag +3%, Induttore V", "DIF Caos, MP +5%")
newWeaponReward("BUNYIPS", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Berserk, DIF Fis +3%")
newWeaponReward("CANNONIERE ALBHED", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Arte medica", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%")
newWeaponReward("CHIMERA", "Perforazione,ATT Mag +5%, ATT Mag +10%, Induttore M", "DIF Mag +10%")
newWeaponReward("CHIMERA", "Perforazione, ATT Mag +5%, ATT Mag +10%, Induttore M", "DIF Mag +10%")
newWeaponReward("CHIMERA BRAIN", "Perforazione, ATT Mag +5%, ATT Mag +10%, Induttore M", "DIF Mag +10%")
newWeaponReward("CONDOR", "Spot, Perforazione, Induttore V", "DIF Blind, DIF Mag +3%")
newWeaponReward("CUSTODE CELESTE", "Perforazione, Consumo 1/2 MP", "MP +10%")
newWeaponReward("CUSTODE DEL LIMBO", "Perforazione, Fuocattacco, Tuonattacco, Acquattacco, Gelattacco", "Immunofuoco, Immunotuono, Immunoacqua, Immunogelo")
newWeaponReward("DEDALARVA", "Perforazione, ATT Sonno", "DIF Sonno, DIF Mag +5%")
newWeaponReward("DEFENDER", "Perforazione, ATT Fis +3%, ATT Fis +5%, Induttore E", "Riserva Protect, DIF Fis +10%")
newWeaponReward("DEFENDER ZERO", "Perforazione, ATT Fis +3%, ATT Fis +5%, ATT Fis +10%, Induttore E", "Riserva Protect, DIF Fis +10%")
newWeaponReward("DEFENSOR", "Perforazione, ATT Fis +3%, ATT Fis +10%, ATT Mag +5%, ATT Mag +10%Induttore E", "Riserva Protect")
newWeaponReward("DEINONYCHUS", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Lentezza, DIF Fis +3%")
newWeaponReward("DEMOMONOLIX", "Perforazione, ATT Pietra, ATT Pietra +", "DIF Pietra, DIF Pietra +, Incontri 0")
newWeaponReward("DESFLOT", "Perforaz., Fuocattac., Tuonattac., Acquattac.,Gelattac., ATT Fis +3%, ATT Mag +3%, Induttore V", "DIF Caos, DIF Caos +, MP+10%")
newWeaponReward("DINGO", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "ATT Mutismo, ATT Sonno, DIF Mag +3%")
newWeaponReward("ECHENEIS", "Perforazione, ATT Fis +3%, ATT Fis +5%", "DIF Zombie, DIF Fis +5%, DIFFis +10%")
newWeaponReward("EFREY", "Perforazione, ATT Pietra", "DIF Pietra")
newWeaponReward("EFREY OLTANA", "Perforazione, ATT Pietra", "DIF Pietra")
newWeaponReward("ELEMENTO BIANCO", "Perforazione, Gelattacco, Induttore M", "Gelo -50%, Immunogelo")
newWeaponReward("ELEMENTO BLU", "Perforazione, Acquattacco, Induttore M", "Acqua -50%, Immunoacqua")
newWeaponReward("ELEMENTO DORATO", "Perforazione, Tuonattacco, Induttore M", "Tuono -50%, Immunotuono")
newWeaponReward("ELEMENTO GIALLO", "Perforazione, Tuonattacco, Induttore M", "Tuono -50%")
newWeaponReward("ELEMENTO NERO", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore M", "Fuoco -50%, Immunofuoco, Tuono -50%,Immunotuono, Immunoacqua, Gelo -50%, Immunogelo")
newWeaponReward("ELEMENTO ROSSO", "Perforazione, Fuocattacco, Induttore M", "Fuoco -50%, Immunofuoco")
newWeaponReward("ELEMENTO SCURO", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore M", "Fuoco -50%, Tuono -50%, Immunotuono, Acqua-50%, Gelo -50%")
newWeaponReward("EPEJ", "Perforazione, ATT Fis +5%, ATT Mag +5%,Riserva Turbo", "DIF Fis +5%")
newWeaponReward("ESPRIT", "Perforazione, ATT Sonno, ATT Sonno +", "DIF Sonno +, DIF Mag +20%")
newWeaponReward("EXORAY", "Perforazione, ATT Sonno, ATT Fis +5%, ATT Mag+5%", "DIF Sonno, MP +10%")
newWeaponReward("FANTASMA", "Perforazione, ATT Mag +5%, ATT Mag +10%,Induttore M", "DIF Morte, MP +10%, Incontri 0")
newWeaponReward("FUNGONGO", "Perforazione, ATT Sonno, ATT Fis +3%, ATT Mag+3%", "DIF Sonno, MP +5%")
newWeaponReward("GALKIMASELA", "Perforazione,Tuonattacco, Induttore M", "Tuono -50%, Immunotuono")
newWeaponReward("GANDHARVA", "Perforazione, Tuonattacco, Induttore M", "Tuono -50%, DIF Mag +3%")
newWeaponReward("GARM", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Mutismo, DIF Sonno, DIF Fis +3%")
newWeaponReward("GARUDA", "Perforazione, ATT Blind, ATTFis +3%, ATT Mag +3%", "DIF Blind")
newWeaponReward("GARUDA", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "DIF Blind")
newWeaponReward("GARUDA", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "DIF Blind")
newWeaponReward("GRANAD", "Perforazione,Fuocattacco, Induttore M", "Fuoco -50%, Immunofuoco")
newWeaponReward("GRAT", "Perforazione, ATT Veleno, ATT Fis +5%, ATT Mag+5%", "DIF Veleno, HP +5%, HP +10%")
newWeaponReward("GRENDEL", "Perforazione, Fuocattacco, ATT Mutismo,Induttore A", "HP +10%")
newWeaponReward("GUARDIA GUADO", "Spot, Perforazione, ATT Fis +3%, ATT Fis +5%,ATT Mag +3%, ATT Mag +5%", "HP +5%, MP +5%, DIF Mag +3%")
newWeaponReward("GUARDIA GUADO", "Spot, Perforazione, ATT Fis +3%, ATT Fis +5%,ATT Mag +3%, ATT Mag +5%", "HP +5%, MP +5%, DIF Mag +3%")
newWeaponReward("GUARDIA GUADO", "Spot, Perforazione, ATT Fis +3%, ATT Fis +5%,ATT Mag +3%, ATT Mag +5%", "HP +5%, MP +5%, DIF Mag +3%")
newWeaponReward("HARUMA", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Berserk, DIF Berserk +")
newWeaponReward("HEG", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Lentezza")
newWeaponReward("HOGA", "Perforazione, ATT Fis +5%, ATT Mag +5%,Contrattacco", "Riserva Haste, HP +10%")
newWeaponReward("IAGUARO", "Perforazione, ATT Morte +, ATT Fis +5%, ATTMag +5%, ATT Mag +10%", "DIF Morte, DIF Fis +10%, DIFMag +10%")
newWeaponReward("IPIRIA", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Lentezza, DIF Fis +3%")
newWeaponReward("JOSGUEIN", "Incontri 0", "Autoreflex")
newWeaponReward("KIMAHRI", "Spot, Perforazione", "DIF Fis +5%")
newWeaponReward("KING BEHEMOTH", "Perforazione, ATT Zombie, Riserva Turbo", "Riserva Shell, Riserva Protect, Riserva Reflex")
newWeaponReward("KUSARIK", "Perforazione, Fuocattacco, Tuonattacco, Acquattacco, Gelattacco,Induttore E", "DIF Lentezza, DIF Fis +5%")
newWeaponReward("KUSHIPOS", "Perforazione, ATT Fis +3%, ATT Mag +3%, Riserva Turbo", "DIF Fis +5%")
newWeaponReward("KUSHIPOS", "Perforazione, Fuocattacco, Induttore E", "Immunofuoco, Mangiafuoco")
newWeaponReward("KYACTUS", "Perforazione, Priorità", "Maratona x HP, Maratona x MP, HP +10%")
newWeaponReward("KYACTUS?", "Perforazione, Priorità, ATT Fis +5%, ATT Mag +5%", "Maratona x HP, Maratona x MP, HP +5%")
newWeaponReward("LANCIATORE ALBHED", "Perforazione, Tuonattacco", "DIF Fis +3%")
newWeaponReward("LARVA", "Perforazione, Tuonattacco", "Tuono -50%")
newWeaponReward("LESMATHOR", "Perforaz.,Fuocattac., Tuonattac., Acquattac., Gelattac., Induttore V, ATT Fis+3%, ATT Mag +3%", "DIF Veleno, MP +5%")
newWeaponReward("LUMBRIKUS", "Perforazione, ATT Lentezza, ATT Lentezza +,ATT Fis +5%, ATT Mag +5%", "HP +10%, Autopozione")
newWeaponReward("LUPO DEL DESERTO", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Mutismo, DIF Sonno, DIF Mag +3%")
newWeaponReward("LUPO DELLE NEVI", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Mutismo, DIF Sonno, DIF Mag +3%")
newWeaponReward("MAFUT", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Berserk, DIF Fis +5%")
newWeaponReward("MAL BERNARDO", "Perforaz.,Fuocattac., Tuonattac., Acquattac., Gelattac., Induttore E, ATT Fis+3%, ATT Mag +3%", "DIF Mutismo, DIF Sonno")
newWeaponReward("MANDRAGORA", "Perforazione, ATT Veleno, ATT Fis +5%, ATT Mag+5%", "DIF Blind, DIFMutismo, DIF Sonno, DIF Veleno, DIF Pietra, DIF Caos, DIF Berserk")
newWeaponReward("MANGIACHOCOBO", "Spot, Perforazione, ATT Fis +5%, ATT Fis +10%,ATT Mag +5%, ATT Mag +10%", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%")
newWeaponReward("MASTER IAGUARO", "Perforazione,ATT Morte, ATT Morte +, ATT Fis +5%, ATT Mag +5%, ATT Mag +10%", "DIF Morte, DIF Morte +, DIF Meledizione +, DIFFis +10%, DIF Mag +10%")
newWeaponReward("MASTRO TOMBERRY", "Perforazione, ATT Morte +, ATT Lentezza +", "DIF Morte, DIF Morte +")
newWeaponReward("MECHY", "Perforazione, ATT Fis +5%, ATT Mag +5%,Riserva Turbo", "DIF Fis +10%, DIF Fis +20%")
newWeaponReward("MERYUJIN", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Lentezza, DIF Fis +3%")
newWeaponReward("MIHEN PHANG", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Mutismo, DIF Sonno")
newWeaponReward("MOLBORO", "Perforazione, ATT Blind, ATT Mutismo, ATTSonno, ATT Veleno", "DIF Blind, DIF Mutismo, DIF Sonno, DIF Veleno,DIF Pietra, DIF Caos, DIF Berserk")
newWeaponReward("MOLBORO IL GRANDE", "Perforazione, ATT Blind, ATT Mutismo, ATTSonno, ATT Veleno", "DIF Blind, DIF Mutismo, DIF Sonno, DIF Veleno,DIF Pietra, DIF Caos, DIF Berserk")
newWeaponReward("MULFUS", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Berserk, DIF Fis +5%")
newWeaponReward("MUSHUHUSHU", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Lentezza, HP +10%")
newWeaponReward("NEBIROS", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Veleno")
newWeaponReward("NEO SEYMOUR", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva Shell")
newWeaponReward("OCCHIO DIABOLICO", "Perforaz.,Fuocattac., Tuonattac., Acquattac., Gelattac., ATT Fis +3%, ATT Mag+3%, Induttore V", "DIF Caos, MP +10%")
newWeaponReward("OCCHIO DIABOLICO", "Perforaz.,Fuocattac., Tuonattac., Acquattac., Gelattac., ATT Fis +3%, ATT Mag+3%, Induttore V", "DIF Caos, MP +10%")
newWeaponReward("OCCHIO FLUTTUANTE", "Perforaz.,Fuocattac., Tuonattac., Acquattac., Gelattac., ATT Fis +3%, ATT Mag+3%, Induttore V", "DIF Caos, MP +10%")
newWeaponReward("OCCHIO MALVAGIO", "Perforaz.,Fuocattac., Tuonattac., Acquattac., Gelattac., ATT Fis +3%, ATT Mag+3%, Induttore V", "DIF Caos, MP +10%")
newWeaponReward("OCHU", "Perforazione, ATT Veleno, ATT Fis +5%, ATT Mag+5%", "DIF Blind, DIF Mutismo, DIF Sonno, DIF Veleno,DIF Pietra, DIF Caos, DIF Berserk")
newWeaponReward("OCHU SMARRITO", "Perforazione, ATT Veleno, ATT Fis +5%, ATT Mag+5%", "DIF Blind, DIF Mutismo, DIF Sonno, DIF Veleno,DIF Pietra, DIF Caos, DIF Berserk")
newWeaponReward("OCTOPUS", "Perforazione, Acquattacco, ATT Fis +5%, ATTMag +5%", "Acqua -50%, HP +5%")
newWeaponReward("OMEGA WEAPON", "Triturbo", "HP Apeiron")
newWeaponReward("PALUDOMAFUT", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Berserk, DIF Fis +5%")
newWeaponReward("PHLEGYAS", "Perforazione, ATT Fis +5%, ATT Mag +5%", "MP +10%, Autopanacea")
newWeaponReward("PIROS", "Perforazione, Fuocattacco, Induttore E", "Fuoco -50%")
newWeaponReward("PIROS", "Perforazione, Fuocattacco, Induttore E", "Fuoco -50%")
newWeaponReward("PORTIERE ALBHED", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva Parafire, Riserva Parathund, RiservaParaidro, Riserva Parabliz")
newWeaponReward("RAMASHUT", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Lentezza, HP +5%")
newWeaponReward("RAPTOR", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Lentezza, DIF Fis +3%")
newWeaponReward("RARTH", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Berserk, DIF Fis +3%")
newWeaponReward("REMORA", "Perforazione, ATT Fis +3%, ATT Fis +5%", "DIF Zombie, DIF Fis +5%")
newWeaponReward("RICEVITORE ALBHED", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Riserva Parafire, Riserva Parathund, RiservaParaidro, Riserva Parabliz")
newWeaponReward("SAHAGIN", "Perforazione, Acquattacco, AFF Fis +3%, ATTMag +3%", "Acqua -50%, HP +5%")
newWeaponReward("SAHAGIN", "Perforazione, Acquattacco, AFF Fis +3%, ATTMag +3%", "Acqua -50%, HP +5%")
newWeaponReward("SCAGLIA EKYU", "Perforazione, Acquattacco", "Acqua -50%")
newWeaponReward("SCAGLIA GHY", "Perforazione, ATT Sonno +", "DIF Sonno +")
newWeaponReward("SCAGLIA GHY", "Perforazione, ATT Sonno +", "DIF Sonno +")
newWeaponReward("SCAGLIA GUNAI", "Perforazione, ATT Zombie +", "DIF Zombie +")
newWeaponReward("SCAGLIA GUNO", "Perforazione, ATT Blind", "DIF Blind")
newWeaponReward("SCOOR", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Mutismo, DIF Sonno")
newWeaponReward("SEYMOUR", "Perforazione, ATT Mutismo +", "DIF Mutismo +")
newWeaponReward("SEYMOUR BETA", "Perforazione, ATT Blind +", "DIF Blind +")
newWeaponReward("SEYMOUR OMEGA", "Perforazione, ATT Mag +20%", "Riserva Shell, Riserva Protect, Riserva Haste")
newWeaponReward("SFEROGESTORE", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%")
newWeaponReward("SHRED", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore E", "DIF Berserk")
newWeaponReward("SHUMELKE", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Lentezza, DIF Fis +5%")
newWeaponReward("SHUMELKE KRYPT", "Perforaz.,Fuocat., Tuonat., Acquat., Gelat., ATT Fis +3%, ATT Fis +5%, ATT Mag+3%, ATT Mag +5%", "DIF Lentezza, DIF Fis +5%")
newWeaponReward("SIGILLO ALBHED", "Perforazione, Tuonattacco", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%")
newWeaponReward("SIMURGH", "Spot, Perforazione, Induttore V", "DIF Blind, DIF Mag +3%")
newWeaponReward("SIN", "Perforazione, Gelattacco", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%")
newWeaponReward("SIN", "Perforazione, ATT Lentezza +", "DIF Lentezza +")
newWeaponReward("SIN", "Perforazione, ATT Blind +, ATT Mutismo +, ATTSonno +, ATT Lentezza +", "DIF Mutismo +")
newWeaponReward("SON", "Perforazione,ATT Sonno, ATT Fis +3%, ATT Fis +5%, ATT Mag +3%, ATT Mag +5%", "DIF Sonno, MP +5%")
newWeaponReward("SPLASHER", "Perforazione, Acquattacco, ATT Fis +5%, ATTMag +5%", "HP +5%, DIF Fis +3%")
newWeaponReward("SPLASHER X2", "Perforazione, Acquattacco, ATT Fis +5%, ATTMag +5%", "HP +5%, DIF Fis +3%")
newWeaponReward("SPLASHER X3", "Perforazione, Acquattacco, ATT Fis +5%, ATTMag +5%", "HP +5%, DIF Fis +3%")
newWeaponReward("TEMPLARE", "Perforazione, ATT Fis +5%, Contramagia", "DIF Morte, DIF Mag +3%")
newWeaponReward("TEMPLARE REDIVIVO", "Perforazione, ATT Fis +5%, Contramagia", "DIF Zombie, DIF Mag +3%")
newWeaponReward("TESTA", "Perforazione, Fuocattacco, Tuonattacco,Acquatacco, Gelattacco", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%")
newWeaponReward("THYTAN", "Perforazione, ATT Fis +5%, ATT Fis +10%, ATTMag +5%, ATT Mag +10%", "Riserva Rigene, HP +5%, HP +10%")
newWeaponReward("TOMBERRY", "Perforazione, ATT Morte, ATT Lentezza", "DIF Morte")
newWeaponReward("ULTIMA WEAPON", "Biturbo", "MP apeiron")
newWeaponReward("ULTRA MIGHT(SPADA STELLA)", "Perforazione, ATT Fis +10%, ATT Mag +10%", "Riserva Rigene, HP +10%")
newWeaponReward("ULTRA MIGHT(SPADA NORMALE)", "Perforazione, ATT Fis +10%, ATT Mag +10%", "Riserva Rigene, HP +10%")
newWeaponReward("UNITA' 97", "Perforazione, ATT Fis +5%, ATT Mag +5%", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%")
newWeaponReward("UNITA' 99", "Fuocat.,Tuonat., Acquat., Gelat., ATT Fis +3%, ATT Fis +5%, ATT Mag +3%, ATTMag +5%, Induttore V", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%")
newWeaponReward("UNITA' BLINDATA 11", "Perforazione, ATT Fis +5%, ATT Mag +5%", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%")
newWeaponReward("UNITA' BLINDATA 63", "Perforazione, ATT Fis +3%, ATT Fis +5%, ATTMag +3%, ATT Mag +5%", "Fuoco -50%, Tuono -50%, Acqua -50%, Gelo -50%")
newWeaponReward("VARAHA", "Perforazione, Fuocattacco, ATT Mutismo,Induttore A", "HP +10%")
newWeaponReward("VARNA", "Perforazione, ATT Mag +10%, Biturbo", "Riserva Shell, DIF Mag +10%")
newWeaponReward("VESPA", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Veleno, MP +10%")
newWeaponReward("VIHUR", "Perforazione, Gelattacco", "DIF Lentezza, HP +5%")
newWeaponReward("VIVRE", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Lentezza, HP +5%")
newWeaponReward("WENDIGO", "Perforazione, Contrattacco", "Riserva Haste, HP +10%")
newWeaponReward("YENKE RONSO", "Perforazione", "MP +20%")
newWeaponReward("YOWIE", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Lentezza")
newWeaponReward("YUNALESCA", "Perforazione, ATT Zombie +", "DIF Zombie +")
newWeaponReward("ZAURAS", "Perforazione, Fuocattacco, Tuonattacco,Acquattacco, Gelattacco, Induttore V", "DIF Lentezza, DIF Lentezza +")
newWeaponReward("ZUU", "Perforazione, ATT Blind, ATT Fis +3%, ATT Mag+3%", "DIF Blind")
newWeaponReward("ZUU", "Perforazione, ATT Blind, ATT Fis +5%, ATT Mag+5%", "DIF Blind")

newStats(["ADAMANTHART", "54400", "40", "12500", "2200", "Energosfera x2", ["Acqua Curativa x1", "Nettare Energetico"], "-"])
newStats(["ALCIONE", "430", "42", "310", "240", "Velocisfera x1, Albhedina x1", ["Lacrimogeno x1", "Lacrimogeno x2"], "-"])
newStats(["ALYADIN", "22222", "3500", "3100", "1070", "Magicosfera x1", ["Ombra d'Oltremondo", "Vento d'Oltremondo"], "Sentenza"])
newStats(["ALYMAN", "2800", "400", "2200", "750", "Velocisfera x1", ["Stricnina x2", "Stricnina x3"], "-"])
newStats(["ANACONDAR", "5800", "70", "1380", "750", "Energosfera x1", ["Granata Fossile x1", "Granata Fossile x2"], "Fossilspiro"])
newStats(["ANELLIDUS", "4500", "100", "2000", "1000", "Abilitosfera x2", ["Neromagilite x1", "Fluido Energetico x2"], "-"])
newStats(["ANIMA", "18000", "50", "2500", "3000", "Abilitosfera x1", ["Mina Tacet x3", "Ombra d'Oltremondo x1"], "-"])
newStats(["APE KILLER", "110", "5", "9", "23", "Velocisfera x1", ["Antidoto x1", "Zanna velenosa x1"], "-"])
newStats(["AQUELOUS", "5100", "85", "730", "420", "Energosfera x1", ["Idromagilite x2", "Fluido Rigenerante x1"], "-"])
newStats(["AROJ", "200", "220", "92", "144", "Magicosfera x1", ["Razzo elettrico x1", "Razzo fulminante x1"], "-"])
newStats(["ASHOOR", "17000", "5", "1860", "730", "Energosfera x1", ["Fluido vitale x1", "Fluido vitale x2"], "-"])
newStats(["AUTOARMATURA", "8700", "1", "950", "880", "Coda di fenice x1", ["Albhedina x2", "Albhedina x3"], "-"])
newStats(["AUTOARTIGLIERE", "2800", "1", "540", "800", "Granpozione x2", ["Albhedina x1", "Albhedina x2"], "-"])
newStats(["AUTOCACCIATORE", "5500", "1", "420", "673", "Coda di fenice x1", ["Albhedina x1", "Albhedina x2"], "-"])
newStats(["AUTOCOMMANDER", "3700", "1", "830", "530", "Granpozione x1", ["Granata x2", "Blindogranata x2"], "-"])
newStats(["AUTOGUARDIANO", "1280", "1", "310", "600", "Granpozione x1", ["Granata fossile x2", "Granata fossile x3"], "-"])
newStats(["AUTOSCOUT", "2750", "1", "480", "384", "Granpozione x1", ["Granata fossile x3", "Granata fossile x3"], "-"])
newStats(["BALSAMIKO", "780", "15", "20", "48", "Magicosfera x1", ["Antidoto x1", "Panacea x1"], "Cerbottana"])
newStats(["BALSAMIKO GRASSO", "12750", "3", "540", "336", "Magicosfera x1", ["Panacea x2", "Stricnina x10"], "Cerbottana"])
newStats(["BARBATOS", "95000", "480", "17500", "1550", "Energosfera x1", ["Cortina stellare x1", "Sacromagilite x1"], "-"])
newStats(["BASILISK", "2025", "20", "140", "125", "Abilitosfera x1", ["Granata fossile x1", "Granata fossile x1"], "Fossilspiro"])
newStats(["BEHEMOTH", "23000", "480", "6540", "1350", "Energosfera x1", ["Etere x1", "Nettare energetico x1"], "Difesa totale"])
newStats(["BIKORNO", "1875", "18", "42", "105", "Abilitosfera x1", ["Pozione x1", "Granpozione x1"], "Pirosbolle"])
newStats(["BIKORNO", "3795", "22", "820", "520", "Abilitosfera x1", ["Granpozione x1", "Megapozione x1"], "Pirosbolle"])
newStats(["BIRAN RONSO", "Variabile", "200", "4500", "1500", "Gamberosfera x1", ["Passosfera Lv 3 x2", "Passosfera Lv 3 x3"], "4 Nemitec diverse"])
newStats(["BOTTE MAGICA", "999999", "999", "0", "0", "-", ["-", "-"], "-"])
newStats(["BRACCIO", "800", "1", "37", "300", "-", ["Pozione x1", "Pozione x1"], "-"])
newStats(["BRACCIO DX DI SIN", "65000", "999", "17000", "10000", "Passosfera Lv 3 x1", ["Extrapozione x1", "Eliomagilite x1"], "-"])
newStats(["BRACCIO SX DI SIN", "65000", "999", "16000", "10000", "Accapisfera x1", ["Megapozione x1", "Examagilite x1"], "-"])
newStats(["BUDINO D'ACQUA", "315", "30", "2", "18", "Magicosfera x1", ["Squame di pesce x1", "Squame di drago x1"], "-"])
newStats(["BUDINO D'ACQUA", "2025", "1", "240", "340", "Magicosfera x1", ["Squame di pesce x2", "Squame di drago x2"], "-"])
newStats(["BUDINO DI FIAMME", "1500", "200", "480", "448", "Magicosfera x1", ["Magmagilite x1", "Magmagilite x2"], "-"])
newStats(["BUDINO DI GHIACCIO", "1350", "160", "300", "188", "Magicosfera x1", ["Vento antartico x1", "Vento antartico x2"], "-"])
newStats(["BUDINO DI NEVE", "600", "120", "48", "93", "Magicosfera x1", ["Vento antartico x1", "Vento antartico x2"], "-"])
newStats(["BUDINO DI TUONO", "450", "50", "24", "50", "Magicosfera x1", ["Razzo elettrico x1", "Razzo elettrico x2"], "-"])
newStats(["BUDINO OSCURO", "12800", "250", "3750", "1080", "Magicosfera x1", ["Cortina stellare x1", "Cortina stellare x2"], "Vento bianco"])
newStats(["BUEL", "230", "250", "92", "132", "Velocisfera x1", ["Granpozione x1", "Stricnina x1"], "-"])
newStats(["BUNYIPS", "400", "15", "48", "97", "Energosfera x1", ["Granpozione x1", "Hypellina x1"], "-"])
newStats(["CANNONIERE ALBHED", "16000", "1", "4400", "7000", "Elisir x1", ["Cortina lunare x1", "Cortina lunare x2"], "-"])
newStats(["CAPITAN SAHAGIN", "170", "5", "2", "20", "Energosfera x1", ["-", "-"], "-"])
newStats(["CHIMERA", "5250", "130", "1220", "970", "Abilitosfera x1", ["Vento Antartico x1", "Razzo Fulminante x1"], "Idrorespiro"])
newStats(["CHIMERA", "9000", "200", "2000", "980", "Abilitosfera x1", ["Vento Antartico x3", "Razzo Fulminante x3"], "Idrorespiro"])
newStats(["CHIMERA BRAIN", "9800", "250", "1200", "1000", "Abilitosfera x1", ["Criomagilite x1", "Elettromagilite x2"], "Idrorespiro"])
newStats(["CONDOR", "95", "15", "2", "12", "Velocisfera x1", ["Coda di Fenice x1", "Lacrimogeno x2"], "-"])
newStats(["CUSTODE CELESTE", "40000", "256", "11000", "6500", "Gamberosfera x1", ["Turboetere x1", "Turboetere x2"], "-"])
newStats(["CUSTODE DEL LIMBO", "52000", "500", "12000", "7000", "Passosfera Lv 4 x1", ["Etere x1", "Turboetere x1"], "-"])
newStats(["DEDALARVA", "2222", "1111", "1850", "620", "Abilitosfera x1", ["Squama di pesce x1", "Squama di pesce x2"], "-"])
newStats(["DEFENDER", "12000", "1", "2700", "1300", "Energosfera x2", ["Cortina Lunare x1", "Cortina Lunare x2"], "-"])
newStats(["DEFENDER ZERO", "42300", "1", "6000", "2400", "Passosfera Lv 2 x1", ["Cortina lunare x2", "Cortina lunare x2"], "-"])
newStats(["DEFENSOR", "64000", "1", "6600", "3500", "Passosfera Lv 2 x2", ["Cortina Lunare x4", "Cortina Lunare x4"], "-"])
newStats(["DEINONYCHUS", "140", "25", "9", "27", "Velocisfera x1", ["Ago dorato x1", "Granata fossile x1"], "-"])
newStats(["DEMOMONOLIX", "45000", "9999", "11000", "1470", "Magicosfera x2", ["Granata fossile x2", "Granata fossile x2"], "-"])
newStats(["DESFLOT", "6700", "520", "7100", "1265", "Magicosfera x2", ["Stricnina x4", "Stricnina x5"], "-"])
newStats(["DINGO", "125", "10", "2", "15", "Energosfera x1", ["Pozione x1", "Melatonina x1"], "-"])
newStats(["ECHENEIS", "10000", "35", "600", "330", "Magicosfera x1", ["Idromagilite x2", "Idromagilite x3"], "-"])
newStats(["EFREY", "32000", "500", "5400", "2600", "Mnerosfera x1", ["Idromagilite x1", "Idromagilite x2"], "-"])
newStats(["EFREY OLTANA", "16384", "200", "5800", "3000", "Mnerosfera x1", ["Idromagilite x2", "Fluido rigenerante x1"], "-"])
newStats(["ELEMENTO BIANCO", "390", "120", "20", "48", "Magicosfera x1", ["Vento artico x1", "Vento artico x2"], "-"])
newStats(["ELEMENTO BLU", "1500", "220", "240", "180", "Magicosfera x1", ["Squame di pesce x2", "Squame di pesce x3"], "-"])
newStats(["ELEMENTO DORATO", "1200", "180", "92", "107", "Magicosfera x1", ["Razzo elettrico x1", "Razzo elettrico x2"], "-"])
newStats(["ELEMENTO GIALLO", "300", "100", "9", "33", "Magicosfera x1", ["Razzo elettrico x1", "Razzo fulminante x1"], "-"])
newStats(["ELEMENTO NERO", "7600", "500", "3150", "1040", "Magicosfera x1", ["Granpozione x1", "Eliomagilite x1"], "-"])
newStats(["ELEMENTO ROSSO", "450", "130", "32", "55", "Magicosfera x1", ["Scheggia di Piros x1", "Scheggia di Piros x2"], "-"])
newStats(["ELEMENTO SCURO", "1800", "280", "810", "520", "Magicosfera x1", ["Spina iperica x1", "Spina iperica x2"], ""])
newStats(["EONE DI BRASKA", "60000", "100", "0", "0", "-", ["Turboetere x1", "Elisir x1"], "-"])
newStats(["EONE DI BRASKA", "120000", "100", "0", "0", "-", ["Turboetere x1", "Elisir x1"], "-"])
newStats(["EPEJ", "8700", "20", "970", "950", "Abilitosfera x2", ["Granpozione x1", "Granpozione x2"], "-"])
newStats(["ESPRIT", "10000", "700", "4300", "1300", "Magicosfera x1", ["Fluido energetico x1", "Fluido energetico x2"], "Vento bianco"])
newStats(["EXORAY", "7400", "300", "2400", "840", "Magicosfera x1", ["Mina Tacet x3", "Etere x1"], "-"])
newStats(["FANTASMA", "9999", "350", "1450", "810", "Magicosfera x1", ["Coda di fenice x1", "Ombra d'Oltremondo x1"], "Sentenza"])
newStats(["FUNGONGO", "540", "60", "44", "42", "Magicosfera x1", ["Mina Tacet x1", "Etere x1"], "-"])
newStats(["GALKIMASELA", "880", "300", "770", "610", "Magicosfera x1", ["Elettromagilite x1", "Elettromagilite x2"], "-"])
newStats(["GANDHARVA", "148", "160", "32", "62", "Magicosfera x1", ["Razzo elettrico x1", "Razzo elettrico x2"], "-"])
newStats(["GARM", "240", "35", "48", "88", "Energosfera x1", ["Granpozione x1", "Melatonina x1"], "-"])
newStats(["GARUDA", "1400", "50", "8", "30", "Energosfera x1", ["-", "-"], "-"])
newStats(["GARUDA", "1800", "10", "28", "0", "Energosfera x1", ["-", "-"], "-"])
newStats(["GARUDA", "4000", "50", "170", "140", "Energosfera x1", ["Lacrimogeno x1", "Lacrimogeno x1"], "-"])
newStats(["GRANAD", "7500", "63", "1350", "540", "Energosfera x1", ["Magmagilite x2", "Magmagilite x3"], "Kamikaze"])
newStats(["GRAT", "4000", "25", "980", "520", "Magicosfera x1", ["Antidoto x4", "Panacea x3"], "Cerbottana"])
newStats(["GRENDEL", "9500", "62", "2600", "730", "Abilitosfera x1", ["Granpozione x1", "Megapozione x1"], "Pirosbolle"])
newStats(["GUARDIA GUADO", "2000", "10", "290", "300", "Abilitosfera x1", ["Granpozione x1", "Etere x1"], "-"])
newStats(["GUARDIA GUADO", "1200", "330", "290", "480", "Abilitosfera x1", ["Granpozione x1", "Extrapozione x1"], "-"])
newStats(["GUARDIA GUADO", "2600", "600", "540", "380", "Abilitosfera x1", ["Granpozione x1", "Extrapozione x2"], "-"])
newStats(["HARUMA", "13000", "1", "5300", "1030", "Energosfera x1", ["Hypellina x3", "Neromagilite x2"], "-"])
newStats(["HEG", "2000", "46", "810", "602", "Energosfera x1", ["Granpozione x1", "Clessidra d'oro x1"], "-"])
newStats(["HOGA", "9400", "3", "1080", "980", "Energosfera x1", ["Fluido energetico x1", "Fluido energetico x2"], "-"])
newStats(["IAGUARO", "6000", "480", "1300", "1100", "Magicosfera x1", ["Fluido magico x1", "Fluido magico x1"], "-"])
newStats(["IPIRIA", "180", "35", "24", "46", "Velocisfera x1", ["Ago dorato x1", "Granata fossile x1"], "-"])
newStats(["JOSGUEIN", "32767", "128", "0", "0", "-", ["-", "-"], "-"])
newStats(["JOSGUEIN", "32767", "128", "4200", "1000", "Energosfera x2", ["Idromagilite x1", "Idromagilite x2"], "-"])
newStats(["KIMAHRI", "750", "10", "3", "100", "Abilitosfera x2", ["-", "-"], "-"])
newStats(["KING BEHEMOTH", "67500", "700", "16800", "1850", "Energosfera x1", ["Fluido rigenerante x1", "Duostella x2"], "-"])
newStats(["KLIK", "1500", "5", "5", "50", "Abilitosfera x2", ["Granata x1", "Granata x2"], "-"])
newStats(["KOBUSHI", "8000", "600", "0", "0", "-", ["-", "-"], "-"])
newStats(["KUSARIK", "445", "31", "92", "111", "Energosfera x1", ["Granpozione x1", "Clessidra d'argento x1"], "-"])
newStats(["KUSHIPOS", "2700", "5", "520", "220", "Abilitosfera x1", ["Granpozione x1", "Megapozione x1"], "-"])
newStats(["KUSHIPOS", "20000", "180", "3200", "970", "Magicosfera x1", ["Magmagilite x3", "Magmagilite x4"], "Kamikaze"])
newStats(["KYACTUS", "800", "1", "8000", "1500", "Velocisfera x2", ["Coda di chocobo x1", "Piuma di chocobo x1"], "-"])
newStats(["KYACTUS?", "500", "1", "350", "1500", "Velocisfera x1", ["Coda di chocobo x1", "Coda di chocobo x1"], "-"])
newStats(["LANCIATORE ALBHED", "6000", "10", "36", "580", "Elisir x1", ["-", "-"], "-"])
newStats(["LARVA", "1498", "1000", "262", "330", "Abilitosfera x1", ["Cortina lunare x1", "Cortina lunare x2"], "-"])
newStats(["LESMATHOR", "200", "10", "40", "62", "Velocisfera x1", ["Antidoto x1", "Zanna velenosa x1"], "-"])
newStats(["LUMBRIKUS", "80000", "160", "22000", "2200", "Energosfera x1", ["Fluido energetico x1", "Fluido energetico x1"], "-"])
newStats(["LUPO DEL DESERTO", "450", "55", "310", "225", "Energosfera x1, Albhedina x1", ["Melatonina x2", "Melatonina x2"], "-"])
newStats(["LUPO DELLE NEVI", "400", "50", "300", "195", "Energosfera x1", ["Melatonina x1", "Melatonina x2"], "-"])
newStats(["MAFUT", "710", "25", "300", "172", "Energosfera x1", ["Granpozione x1", "Hypellina x1"], "-"])
newStats(["MAL BERNARDO", "1800", "75", "820", "880", "Energosfera x1", ["Onirolina x2", "Onirolina x3"], "-"])
newStats(["MANDRAGORA", "31000", "120", "6230", "1200", "Magicosfera x1", ["Panacea x2", "Panacea x3"], "-"])
newStats(["MANGIACHOCOBO", "10000", "5", "90", "970", "Passosfera Lv 1 x2", ["Pozione x1", "Pozione x1"], "-"])
newStats(["MASTER IAGUARO", "13000", "540", "6500", "2030", "Passosfera Lv 1 x1", ["Ombra d'Oltremondo x2", "Ombra d'Oltremondo x4"], "-"])
newStats(["MASTRO TOMBERRY", "48000", "1", "20000", "2400", "Energosfera x1", ["Fluido magico x1", "Tetraelementale x1"], "-"])
newStats(["MECHY", "18000", "59", "83000", "1450", "Magicosfera x1", ["Granpozione x2", "Filtro energetico x1"], "-"])
newStats(["MEKALUNIO", "4000", "512", "0", "0", "-", ["-", "-"], "-"])
newStats(["MERYUJIN", "265", "65", "92", "108", "Velocisfera x1", ["Ago dorato x1", "Granata fossile x1"], "-"])
newStats(["MIHEN PHANG", "160", "20", "20", "33", "Energosfera x1", ["Pozione x1", "Melatonina x1"], "-"])
newStats(["MIMIK", "60000", "10", "0", "50000", "-", ["-", "-"], "-"])
newStats(["MIMIK", "40000", "10", "0", "50000", "-", ["-", "-"], ""])
newStats(["MIMIK", "40000", "10", "0", "50000", "-", ["-", "-"], "-"])
newStats(["MIMIK", "40000", "10", "0", "50000", "-", ["-", "-"], "-"])
newStats(["MOLBORO", "27000", "1", "2300", "1500", "Magicosfera x2", ["Panacea x1", "Panacea x1"], "Alito fetido"])
newStats(["MOLBORO IL GRANDE", "64000", "1", "21000", "1900", "Magicosfera x1", ["Panacea x1", "Nettare magico x1"], "Alito fetido"])
newStats(["MULFUS", "580", "20", "240", "165", "Energosfera x1", ["Granpozione x1", "Hypellina x1"], "-"])
newStats(["MUSHUHUSHU", "680", "38", "310", "270", "Energosfera x1, Albhedina x1", ["Granpozione x1", "Clessidra d'argento x1"], "-"])
newStats(["NEBIROS", "700", "65", "480", "320", "Magicosfera x1", ["Zanna velenosa x1", "Zanna velenosa x2"], "-"])
newStats(["NEO SEYMOUR", "36000", "200", "6300", "3500", "Passosfera Lv 2 x2", ["Tetraelementale x2", "Tetraelementale x3"], "-"])
newStats(["NEOLUNIO", "4000", "50", "0", "0", "-", ["-", "-"], "-"])
newStats(["OCCHIO DIABOLICO", "310", "300", "300", "205", "Velocisfera x1", ["Granpozione x1", "Stricnina x1"], "-"])
newStats(["OCCHIO DIABOLICO", "430", "310", "480", "220", "Velocisfera x1", ["Stricnina x1", "Stricnina x2"], "-"])
newStats(["OCCHIO FLUTTUANTE", "140", "200", "21", "44", "Velocisfera x1", ["Erba dell'eco x1", "Stricnina x1"], "-"])
newStats(["OCCHIO MALVAGIO", "380", "280", "240", "320", "Velocisfera x1", ["Granpozione x1", "Mina Tacet x2"], "-"])
newStats(["OCHU", "7200", "35", "180", "520", "Energosfera x1", ["Panacea x1", "Panacea x2"], "."])
newStats(["OCHU SMARRITO", "4649", "39", "40", "420", "Emmepisfera x1", ["Pozione x1", "Pozione x1"], "-"])
newStats(["OCTOPUS", "4500", "1", "700", "220", "Magicosfera x1", ["Squame di drago x2", "Idromagilite x2"], "-"])
newStats(["OMEGA WEAPON", "999999", "999", "50000", "30000", "Passosfera Lv 4 x3", ["Anima del baro x30", "Anima del baro x30"], "Sunshine"])
newStats(["PAGODA YU", "5000", "5000", "0", "0", "-", ["-", "-"], "-"])
newStats(["PALUDOMAFUT", "850", "1", "240", "290", "Energosfera x1", ["Granpozione x1", "Hypellina x1"], "-"])
newStats(["PHLEGYAS", "1680", "50", "650", "410", "Energosfera x1", ["Squame di drago x2", "Idromagilite x1"], "-"])
newStats(["PIRANHA", "50", "1", "1", "2", "Energosfera x1", ["Granata x1", "Granata x2"], "-"])
newStats(["PIRANHA X2", "100", "2", "1", "3", "Magicosfera x1", ["Granata x1", "Granata x2"], "-"])
newStats(["PIRANHA X3", "150", "3", "1", "5", "Velocisfera x1", ["Granata x1", "Granata x2"], "-"])
newStats(["PIROS", "850", "30", "22", "70", "Energosfera x1", ["Scheggia di Piros x2", "Scheggia di Piros x3"], "Kamikaze"])
newStats(["PIROS", "2200", "45", "620", "470", "Energosfera x1", ["Anima di Piros x2", "Anima di Piros x3"], "Kamikaze"])
newStats(["PORTIERE ALBHED", "300", "1", "7", "85", "Granpozione x1", ["-", "-"], "-"])
newStats(["RAMASHUT", "275", "21", "32", "72", "Energosfera x1", ["Pozione x1", "Clessidra d'argento x1"], "-"])
newStats(["RAPTOR", "200", "45", "32", "48", "Velocisfera x1", ["Ago dorato x1", "Granata fossile x1"], "-"])
newStats(["RARTH", "240", "10", "20", "42", "Energosfera x1", ["Pozione x1", "Hypellina x1"], "-"])
newStats(["REMORA", "3000", "22", "830", "535", "Magicosfera x1", ["Squame di drago x1", "Squame di drago x2"], "-"])
newStats(["RICEVITORE ALBHED", "4000", "10", "660", "2400", "Megafenice x1", ["Pozione x1", "Pozione x1"], "-"])
newStats(["SAHAGIN", "100", "5", "0", "0", "-", ["-", "-"], "-"])
newStats(["SAHAGIN", "1380", "20", "200", "180", "Energosfera x1", ["Squame di pesce x2", "Squame di drago x2"], "-"])
newStats(["SAHAGIN", "380", "20", "460", "200", "Energosfera x1", ["Squame di pesce x1", "Squame di drago x1"], "-"])
newStats(["SCAGLIA EKYU", "2000", "20", "12", "115", "Abilitosfera x2", ["-", "-"], "-"])
newStats(["SCAGLIA EMUZU", "2400", "400", "0", "0", "-", ["-", "-"], "-"])
newStats(["SCAGLIA GHY", "12000", "30", "400", "1000", "-", ["Pozione x1", "Pozione x1"], "-"])
newStats(["SCAGLIA GHY", "6000", "30", "0", "1000", "Passosfera Lv 1 x3", ["Pozione x1", "Pozione x1"], "-"])
newStats(["SCAGLIA GUNAI", "20000", "200", "1800", "10000", "Gamberosfera x1", ["Cortina stellare x1", "Eliomagilite x1"], "-"])
newStats(["SCAGLIA GUNO", "3000", "30", "48", "300", "Energosfera x2", ["-", "-"], "-"])
newStats(["SCOOR", "1000", "60", "480", "420", "Energosfera x1", ["Onirolina x1", "Onirolina x2"], "-"])
newStats(["SEYMOUR", "6000", "100", "2000", "5000", "Mnerosfera x1", ["Turboetere x1", "Elisir x1"], "-"])
newStats(["SEYMOUR BETA", "70000", "512", "10000", "6000", "Passosfera Lv 4 x1", ["Elisir x1", "Elisir x1"], "-"])
newStats(["SEYMOUR OMEGA", "80000", "999", "24000", "12000", "Passosfera Lv 3 x1", ["Eliomagilite x1", "Examagilite x1"], "-"])
newStats(["SFEROGESTORE", "12000", "100", "3240", "4000", "Passosfera Lv 2 x1", ["Etere x1", "Turboetere x1"], "-"])
newStats(["SHRED", "1950", "30", "480", "368", "Velocisfera x1", ["Hypellina x1", "Hypellina x2"], "-"])
newStats(["SHUMELKE", "370", "70", "240", "138", "Velocisfera x1", ["Ago dorato x1", "Granata fossile x1"], "-"])
newStats(["SHUMELKE KRYPT", "550", "1", "240", "300", "Velocisfera x1", ["Ago dorato x1", "Granata fossile x1"], "-"])
newStats(["SIGILLO ALBHED", "1000", "1", "220", "300", "Pozione x1", ["Granpozione x1", "Granpozione x2"], "-"])
newStats(["SIMURGH", "200", "27", "48", "73", "Velocisfera x1", ["Lacrimogeno x1", "Lacrimogeno x2"], "-"])
newStats(["SIN", "2000", "100", "10", "100", "Magicosfera x1", ["-", "-"], "-"])
newStats(["SIN", "36000", "999", "18000", "1000", "Emmepisfera x1", ["Fluido energetico x3", "Fluido energetico x4"], "-"])
newStats(["SIN", "140000", "999", "20000", "12000", "Passosfera Lv 3 x1", ["Etere x1", "Examagilite x1"], "-"])
newStats(["SON", "4080", "120", "830", "530", "Magicosfera x1", ["Mina Tacet x2", "Etere x1"], "-"])
newStats(["SPLASHER", "200", "2", "140", "100", "Energosfera x1", ["Granata x1", "Blindogranata x1"], "-"])
newStats(["SPLASHER X2", "400", "4", "300", "140", "Energosfera x1", ["Granata x1", "Blindogranata x1"], "-"])
newStats(["SPLASHER X3", "600", "6", "440", "200", "Energosfera x1", ["Granata x1", "Blindogranata x1"], "-"])
newStats(["TEMPLARE", "1400", "20", "420", "460", "Abilitosfera x1", ["Granpozione x2", "Sale purificatore x1"], "-"])
newStats(["TEMPLARE", "1400", "20", "420", "460", "Abilitosfera x1", ["Granpozione x2", "Sale purificatore x1"], "-"])
newStats(["TEMPLARE REDIVIVO", "3300", "1", "1200", "540", "Abilitosfera x1", ["Candela della vita x2", "Sale purificatore x1"], "-"])
newStats(["TEMPLARE REDIVIVO", "3300", "1", "1200", "540", "Abilitosfera x1", ["Candela della vita x2", "Sale purificatore x1"], "-"])
newStats(["TENTACOLO DI GUNO", "450", "10", "5", "30", "Abilitosfera x1", ["-", "-"], "-"])
newStats(["TESTA", "4000", "200", "48", "200", "-", ["Pozione x1", "Pozione x1"], "-"])
newStats(["THROS", "2200", "10", "8", "100", "Energosfera x2", ["Granata x1", "Granata x3"], "-"])
newStats(["THYTAN", "3600", "1", "800", "600", "Energosfera x2", ["Cortina luminosa x1", "Cortina luminosa x1"], "-"])
newStats(["TOMBERRY", "13500", "1", "6500", "2000", "Energosfera x1", ["Granpozione x1", "Ombra d'Oltremondo x1"], "-"])
newStats(["TRITO DI SCAGLIA", "100", "0", "0", "0", "-", ["-", "-"], "-"])
newStats(["TRITO DI SCAGLIA", "200", "0", "2", "22", "Energosfera x1", ["-", "-"], "-"])
newStats(["TRITO DI SCAGLIA", "100", "0", "2", "24", "Magicosfera x1", ["-", "-"], ""])
newStats(["TSUBASA", "12000", "1000", "0", "0", "-", ["-", "-"], "-"])
newStats(["TSURUGI", "20000", "1500", "0", "0", "-", ["-", "-"], "-"])
newStats(["ULTIMA WEAPON", "70000", "1", "40000", "20000", "Passosfera Lv 3 x3", ["Porta sul domani x10", "Porta sul domani x20"], "-"])
newStats(["ULTRA MIGHT(SPADA STELLA)", "36000", "1", "7800", "1111", "Energosfera x1", ["Cortina lunare x1", "Cortina lunare x2"], "-"])
newStats(["ULTRA MIGHT(SPADA NORMALE)", "36000", "1", "7800", "1111", "Energosfera x1", ["Cortina lunare x1", "Cortina lunare x2"], "-"])
newStats(["UNITA' 97", "3700", "1", "3200", "1080", "Coda di fenice x2", ["Acquasanta x3", "Etere x2"], "-"])
newStats(["UNITA' 99", "2700", "1", "1870", "1300", "Coda di fenice x1", ["Panacea x1", "Etere x1"], "-"])
newStats(["UNITA' BLINDATA 11", "6200", "1", "3200", "1080", "Granpozione x2", ["Acquasanta x3", "Etere x2"], "Mawashigeri"])
newStats(["UNITA' BLINDATA 63", "6200", "1", "1870", "1300", "Granpozione x1", ["Panacea x1", "Etere x1"], "Mawashigeri"])
newStats(["VARAHA", "8700", "29", "1320", "720", "Abilitosfera x1", ["Granpozione x1", "Granpozione x2"], "Pirosbolle"])
newStats(["VARNA", "56000", "1", "19500", "1780", "Magicosfera x1", ["Vento d'Oltremondo x1", "Eliomagilite x1"], "-"])
newStats(["VESPA", "360", "30", "240", "142", "Velocisfera x1", ["Granpozione x1", "Zanna velenosa x1"], "-"])
newStats(["VIHUR", "225", "1", "14", "50", "Energosfera x1", ["-", "-"], "-"])
newStats(["VIVRE", "225", "22", "24", "60", "Energosfera x1", ["Pozione x1", "Clessidra d'argento x1"], "-"])
newStats(["WENDIGO", "18000", "32", "2000", "3000", "Energosfera x1", ["Granpozione x1", "Extrapozione x1"], "-"])
newStats(["YENKE RONSO", "Variabile", "200", "4500", "1500", "Gamberosfera x1", ["Passosfera Lv 3 x1", "Passosfera Lv 3 x2"], "4 Nemitec diverse"])
newStats(["YOJIMBO", "33000", "2000", "0", "0", "-", ["-", "-"], "-"])
newStats(["YOWIE", "900", "95", "810", "480", "Velocisfera x1", ["Ago dorato x1", "Granata fossile x1"], "-"])
newStats(["YUNALESCA", "24000", "500", "0", "0", "Passosfera Lv 3 x1", ["Nettare energetico x1", "Vento d'Oltremondo x1"], "-"])
newStats(["YUNALESCA", "48000", "500", "0", "0", "Passosfera Lv 3 x1", ["Nettare energetico x1", "Vento d'Oltremondo x1"], "-"])
newStats(["YUNALESCA", "60000", "500", "14000", "9000", "Passosfera Lv 3 x1", ["Nettare energetico x1", "Vento d'Oltremondo x1"], "-"])
newStats(["ZAURAS", "7850", "1", "5000", "950", "Velocisfera x1", ["Granata fossile x2", "Granata fossile x3"], ""])
newStats(["ZUU", "12000", "50", "1200", "1200", "Energosfera x1, Albhedina x1", ["Lacrimogeno x3", "Lacrimogeno x4"], "-"])
newStats(["ZUU", "18000", "50", "1200", "1200", "Energosfera x1, Albhedina x1", ["Lacrimogeno x3", "Lacrimogeno x4"], "-"])


newChampion('Campioni di zona', 'Trusthevis', '99 Filtri energetici', { zoneRequired: 'Besaid', stats: { hp: '320.000', uc: '10.000', mp: '115', ruba: { normale: 'Lacrimogeno x 3', raro: 'Filtro energetico x 2' }, oggetto: 'Amuleto x 2', debolezza: 'RES 0% a Spot, Scan, Antima, Moviola e Spazzata, e RES 90% a Zombie ed Anti' } })
newChampion('Campioni di zona', 'Molboro Beta', '99 Zanne velenose', { zoneRequired: 'Kilika', stats: { hp: '640.000', uc: '12.000', mp: '200', ruba: { normale: 'Panacea x 4', raro: 'Fluido magico x 2' }, oggetto: 'Filtro magico x 2', debolezza: 'Fuoco x1.5, assorbe acqua' } })
newChampion('Campioni di zona', 'Kolossos', '99 Fluidi vitali', { zoneRequired: 'Via Mihen', stats: { hp: '440.000', uc: '15.000', mp: '20', ruba: { normale: 'Fluido energetico x 4', raro: 'Fluido vitale x 2' }, oggetto: 'Fluido rigenerante x 20' } })
newChampion('Campioni di zona', 'Iaguaro regina', '99 Candele della vita', { zoneRequired: 'Via Micorocciosa', stats: { hp: '380.000', uc: '10.000', mp: '80', ruba: { normale: 'Vento d\'Oltremondo x 2', raro: 'Sacromagilite x 1' }, oggetto: 'Eliomagilite x 3' } })
newChampion('Campioni di zona', 'Yormungand', '99 Granate fossili', { zoneRequired: 'Via Djose', stats: { hp: '520.000', uc: '10.000', mp: '63', ruba: { normale: 'Granata fossile x 4', raro: 'Triostella x 1' }, oggetto: 'Examagilite x 2', debolezza: 'RES 0% a Zombie, e RES 90% agli Anti' } })
newChampion('Campioni di zona', 'Kyactus', '99 Piume di Chocobo', { zoneRequired: 'Piana dei Lampi', stats: { hp: '100.000', uc: '10.000', mp: '0', ruba: { normale: 'Piuma di chocobo x 2', raro: 'Portafoglio gonfio x 1' }, oggetto: 'Sacromagilite x 3' } })
newChampion('Campioni di zona', 'Espada', '99 Eliomagiliti', { zoneRequired: 'Macalania', stats: { hp: '280.000', uc: '15.000', mp: '120', ruba: { normale: 'Ombra d\'Oltremondo x 4', raro: 'Vento d\'Oltremondo x 1' }, oggetto: 'Carta d\'identità x 1', debolezza: 'RES 0% agli Anti e RES 50% a Zombie' } })
newChampion('Campioni di zona', 'Abyss Worm', '99 Neromagiliti', { zoneRequired: 'Bikanel', stats: { hp: '480.000', uc: '12.000', mp: '200', ruba: { normale: 'Neromagilite x 4', raro: 'Nettare energetico x 1' }, oggetto: 'Filtro energetico x 1' } })
newChampion('Campioni di zona', 'Chimera X', 'Vento d\'Oltremondo x 60', { zoneRequired: 'Piana della Bonaccia', stats: { hp: '120.000', uc: '10.000', mp: '30', ruba: { normale: 'Filtro magico x 2', raro: 'Fluido energetico x 2' }, oggetto: 'Gamberosfera x 1', debolezza: 'RES 50% agli Anti' } })
newChampion('Campioni di zona', 'Don Tomberry', 'Clessidre d\'40 argento', { zoneRequired: 'Grotta del Crepaccio', stats: { hp: '480.000', uc: '10.000', mp: '120', ruba: { normale: 'Candela della vita x 2', raro: 'Portafoglio gonfio x 1' }, oggetto: 'Vento d\'Oltremondo x 3' } })
newChampion('Campioni di zona', 'Catoblepas', 'Corona di Boccioli', { zoneRequired: 'Monte Gagazet', stats: { hp: '550.000', uc: '10.000', mp: '160', ruba: { normale: 'Fluido rigenerante x 3', raro: 'Filtro energetico x 1' }, oggetto: 'Triostella x 1', debolezza: 'RES 50% agli Anti' } })
newChampion('Campioni di zona', 'Abadon', '99 Cortie lunari', { zoneRequired: 'Dentro Sin', stats: { hp: '380.000', uc: '10.000', mp: '780', ruba: { normale: 'Sale purificatore x 3', raro: 'Eliomagilite x 1' }, oggetto: 'Nettare magico x 1' } })
newChampion('Campioni di zona', 'Vorban', 'Portafoglio gonfio x 60', { zoneRequired: 'Rovine di Omega', stats: { hp: '630.000', uc: '10.000', mp: '120', ruba: { normale: 'Fluido rigenerante x 2', raro: 'Nettare energetico x 1' }, oggetto: 'Empatosfera x 1' } })

newChampion('Campioni di specie', 'Fenril', '99 Code di Chocobo', { kindRequired: true, fiendsForKind: 3, stats: { hp: '850.000', uc: '99.999', mp: '300', ruba: { normale: 'Coda di Chocobo x 2', raro: 'Piuma di Chocobo x 1' }, oggetto: 'Rapidosfera x 1' } })
newChampion('Campioni di specie', 'Ornitorestes', '99 Fluidi energetici', { kindRequired: true, fiendsForKind: 3, stats: { hp: '800.000', uc: '99.999', mp: '300', ruba: { normale: 'Carta d\'Identità x 1', raro: 'Piuma di Chocobo x 1' }, oggetto: 'Anima del baro x 2' } })
newChampion('Campioni di specie', 'Pterix', '99 Megafenici', { kindRequired: true, fiendsForKind: 4, stats: { hp: '100.000', uc: '99.999', mp: '0', ruba: { normale: 'Lacrimogeno x 4', raro: 'Candela della vita x 1' }, oggetto: 'Destrosfera x 1', debolezza: 'RES 90% agli Anti' } })
newChampion('Campioni di specie', 'Honet', '60 Filtri magici', { kindRequired: true, fiendsForKind: 4, stats: { hp: '620.000', uc: '50.000', mp: '180', ruba: { normale: 'Zanna velenosa x 4', raro: 'Sale purificatore x 2' }, oggetto: 'Mirasfera x 1', debolezza: 'RES 0% a Mutismo, RES 95% agli Anti' } })
newChampion('Campioni di specie', 'Vizalsha', '99 Fluidi magici', { kindRequired: true, fiendsForKind: 4, stats: { hp: '95.000', uc: '10.000', mp: '840', ruba: { normale: 'Elettromagilite x 4', raro: 'Filtro magico x 1' }, oggetto: 'Emmepisfera x 1', debolezza: 'RES 80% ad Antikelesis e Antimajix, RES 99% ad Antiscutum' } })
newChampion('Campioni di specie', 'Unioculum', '60 Nettari energetici', { kindRequired: true, fiendsForKind: 4, stats: { hp: '150.000', uc: '15.000', mp: '270', ruba: { normale: 'Cortina lunare x 3', raro: 'Sacromagilite x 1' }, oggetto: 'Difesfera mag x 1', debolezza: 'RES 0% a Antivis e Antikelesis' } })
newChampion('Campioni di specie', 'Budino Jumbo', '60 Duostelle', { kindRequired: true, fiendsForKind: 3, stats: { hp: '1.300.000', uc: '99.999', mp: '999', ruba: { normale: 'Cortina lunare x 4', raro: 'Nettare magico x 1' }, oggetto: 'Potesfera mag x 1' } })
newChampion('Campioni di specie', 'Elemento Nega', '99 Cortine Stellari', { kindRequired: true, fiendsForKind: 3, stats: { hp: '1.300.000', uc: '15.000', mp: '20', ruba: { normale: 'Cortina lunare x 4', raro: 'Duostella x 1' }, oggetto: 'Duostella x 2' } })
newChampion('Campioni di specie', 'Tanket', '99 Clessidre d\'oro', { kindRequired: true, fiendsForKind: 3, stats: { hp: '900.000', uc: '10.000', mp: '0', ruba: { normale: 'Cortina luminosa x 4', raro: 'Cortina lunare x 4' }, oggetto: 'Difesfera fis x 1' } })
newChampion('Campioni di specie', 'Fefnil', '99 Sali Purificatori', { kindRequired: true, fiendsForKind: 4, stats: { hp: '1.100.000', uc: '13.000', mp: '30', ruba: { normale: 'Clessidra d\'oro x 2', raro: 'Fluido energetico x 2' }, oggetto: 'Cortina luminosa x 20' } })
newChampion('Campioni di specie', 'Sonnellino', '99 Fluidi rigeneranti', { kindRequired: true, fiendsForKind: 5, stats: { hp: '98.000', uc: '10.000', mp: '820', ruba: { normale: 'Zanna velenosa x 4', raro: 'Vento d\'Oltremondo x 1' }, oggetto: 'Telesfera x 1', debolezza: 'RES 0% ad Antivis' } })
newChampion('Campioni di specie', 'Re Piros', '60 Turboetere', { kindRequired: true, fiendsForKind: 5, stats: { hp: '480.000', uc: '10.000', mp: '780', ruba: { normale: 'Magmagilite x 4', raro: 'Eliomagilite x 1' }, oggetto: 'Porta sul domani x 1' } })
newChampion('Campioni di specie', 'Juggernaut', '99 Cortine luminose', { kindRequired: true, fiendsForKind: 5, stats: { hp: '1.200.000', uc: '15.000', mp: '20', ruba: { normale: 'Cortina lunare x 4', raro: 'Eliomagilite x 1' }, oggetto: 'Potesfera fis x 1', debolezza: 'RES 95% agli Anti' } })
newChampion('Campioni di specie', 'Clod d\'acciaio', '90 Nettari Magici', { kindRequired: true, fiendsForKind: 10, stats: { hp: '2.000.000', uc: '99.999', mp: '0', ruba: { normale: 'Cortina luminosa x 4', raro: 'Nettare energetico x 1' }, oggetto: 'Accapisfera x 1', debolezza: 'RES 95% a Antikelesis, Antiscutum e Antimajix' } })

newChampion('Prototipi Zoolab', 'Mangiaterra', '60 Triostelle', { stats: { hp: '1.300.000', uc: '99.999', mp: '30', ruba: { normale: '', raro: 'Passosfera Lv 1 x 1' }, oggetto: 'Fatosfera x 1' } })
newChampion('Prototipi Zoolab', 'Titanosfera', '60 Examagiliti', { stats: { hp: '1.500.000', uc: '99.999', mp: '999', ruba: { normale: '', raro: 'Gamberosfera x 1' }, oggetto: 'Fortunosfera x 1' } })
newChampion('Prototipi Zoolab', 'Catastrophe', '99 Porte sul domani', { stats: { hp: '2.200.000', uc: '99.999', mp: '380', ruba: { normale: '', raro: 'Passosfera Lv 2 x 1' }, oggetto: 'Portafoglio gonfio x 1' } })
newChampion('Prototipi Zoolab', 'Vlakorados', '99 Anime del baro', { stats: { hp: '3.000.000', uc: '99.999', mp: '85', ruba: { normale: '', raro: 'Telesfera x 1' }, oggetto: 'Controchiave x 1' } })
newChampion('Prototipi Zoolab', 'Gasteropodos', '99 Equazioni cubiche', { stats: { hp: '4.000.000', uc: '12.000', mp: '999', ruba: { normale: '', raro: 'Empatosfera x 1' }, oggetto: 'Pendulum x 1', debolezza: 'RES 0% a Mutismo' } })
newChampion('Prototipi Zoolab', 'Ultima X', '99 Materioscure', { stats: { hp: '5.000.000', uc: '99.999', mp: '140', ruba: { normale: '', raro: 'Passosfera Lv 3 x 1' }, oggetto: 'Equazione cubica x 1' } })
newChampion('Prototipi Zoolab', 'Shinryu', '30 Megaelisir', { stats: { hp: '2.000.000', uc: '99.999', mp: '72', ruba: { normale: '', raro: 'Triostella x 1' }, oggetto: 'Ali per l\'ignoto x 1' } })
newChampion('Prototipi Zoolab', 'Il Supremo', '10 Mastersfere', { stats: { hp: '10.000.000', uc: '99.999', mp: '9.999', ruba: { normale: 'Passosfera Lv 4 x 1', raro: 'Onnisfera x 1' }, oggetto: 'Onnisfera x 1' } })

// //rinoadiary
// function printWeapons() {
//   function replaceExtraSpaces(string) {
//     return string.replace(/\n/g, '')
//       .replace(/\s{2,}/g, '')
//       .replace(/^\s/, '')
//       .replace(/\s$/, '')
//   }
//   const tabelle = document.querySelectorAll('table.bestiario')
//   for (let i = 0; i < tabelle.length; i++) {
//     console.log([
//       tabelle[i].querySelector('strong').textContent,
//       replaceExtraSpaces(tabelle[i].querySelectorAll('td[colspan="7"]')[0].textContent),
//       replaceExtraSpaces(tabelle[i].querySelectorAll('td[colspan="7"]')[1].textContent)
//     ])
//   }
// }
// printWeapons()

// function printStats() {
//   function replaceExtraSpaces(string) {
//     return string.replace(/\n/g, '')
//       .replace(/\s{2,}/g, '')
//       .replace(/^\s/, '')
//       .replace(/\s$/, '')
//   }
//   const tdText = (index, array) => replaceExtraSpaces(array[index].textContent)
//   const tableList = document.querySelectorAll('table.bestiario')
//   for (let i = 0; i < tableList.length; i++) {
//     let tds = tableList[i].querySelectorAll('td')
//     console.log([
//       // nome, hp, mp, ap, guil, oggetto, [ruba normale, ruba raro], nemitec
//       tdText(0, tds),
//       tdText(2, tds),
//       tdText(4, tds),
//       tdText(34, tds),
//       tdText(36, tds),
//       tdText(42, tds),
//       [tdText(46, tds), tdText(48, tds)],
//       tdText(51, tds)
//     ]);
//   }
// }
// printStats()

fs.writeFileSync(`${__dirname}/zoolab.json`, JSON.stringify(zoolab))
